
import { revalidatePath } from '@/src/react-app/compat/cache';
import { redirect } from '@/src/react-app/compat/navigation';
import { isLocale, type Locale } from '@/src/i18n/config';
import { requireRoles } from '@/src/lib/auth/context';
import { getSupabaseBrowserClient } from '@/src/lib/supabase/browser';
import { bookingUpdateSchema, offerDecisionSchema, offerSchema } from './validation';

export interface JourneyActionState { error?: string; success?: string }
const providerRoles = ['PROVIDER','HOSPITAL_ADMIN','HOSPITAL_COORDINATOR','PHARMACY','DOCTOR','ADMIN','SUPER_ADMIN'] as const;
function localeFrom(data: FormData): Locale { const value=String(data.get('locale')??'en'); return isLocale(value)?value:'en'; }
const lines = (value: string) => value.split(/\r?\n/).map((item)=>item.trim()).filter(Boolean);
const emptyToNull = (value: string | undefined) => value || null;

export async function saveOfferAction(_state: JourneyActionState, formData: FormData): Promise<JourneyActionState> {
  const locale=localeFrom(formData); const context=await requireRoles(locale, providerRoles); const raw=Object.fromEntries(formData); const parsed=offerSchema.safeParse(raw); if(!parsed.success)return{error:'invalid'}; const supabase=await getSupabaseBrowserClient(); if(!supabase)return{error:'unavailable'};
  const value=parsed.data; const payload:Record<string,unknown>={...value, recommendation_id:value.recommendation_id, doctor_id:value.doctor_id, estimated_stay_days:value.estimated_stay_days??null, proposed_start_date:emptyToNull(value.proposed_start_date), proposed_end_date:emptyToNull(value.proposed_end_date), included_services:lines(value.included_services), excluded_services:lines(value.excluded_services), provider_notes:emptyToNull(value.provider_notes), valid_until:new Date(value.valid_until).toISOString()};
  const offerId=String(formData.get('offer_id')??''); let result;
  if(offerId) result=await supabase.from('offers').update(payload).eq('id',offerId).eq('status','DRAFT').select('id').single(); else result=await supabase.from('offers').insert({...payload,created_by:context.userId,status:'DRAFT'}).select('id').single();
  if(result.error||!result.data)return{error:'save'}; revalidatePath(`/${locale}/provider`); revalidatePath(`/${locale}/doctor`); redirect(`/${locale}/${context.roles.includes('DOCTOR')&&!context.roles.some(r=>r==='PROVIDER'||r.startsWith('HOSPITAL')||r==='PHARMACY')?'doctor':'provider'}/offers/${result.data.id}`);
}
export async function setOfferStatusAction(formData: FormData) { const locale=localeFrom(formData); await requireRoles(locale,providerRoles); const id=String(formData.get('offer_id')??''); const status=String(formData.get('status')??''); if(!id||!['SENT','WITHDRAWN'].includes(status))return; const supabase=await getSupabaseBrowserClient(); if(!supabase)return; await supabase.from('offers').update({status}).eq('id',id); revalidatePath(`/${locale}/provider`); revalidatePath(`/${locale}/doctor`); }
export async function markOfferViewedAction(offerId:string,locale:Locale){ await requireRoles(locale,['PATIENT']); const supabase=await getSupabaseBrowserClient(); if(!supabase)return; await supabase.from('offers').update({status:'VIEWED'}).eq('id',offerId).eq('status','SENT'); revalidatePath(`/${locale}/patient/offers/${offerId}`); }
export async function decideOfferAction(_state:JourneyActionState,formData:FormData):Promise<JourneyActionState>{const locale=localeFrom(formData);await requireRoles(locale,['PATIENT']);const parsed=offerDecisionSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:'invalid'};const supabase=await getSupabaseBrowserClient();if(!supabase)return{error:'unavailable'};const {error}=await supabase.from('offers').update({status:parsed.data.decision,decision_note:parsed.data.decision_note||null}).eq('id',parsed.data.offer_id).in('status',['SENT','VIEWED']);if(error)return{error:'decision'};revalidatePath(`/${locale}/patient/offers`);revalidatePath(`/${locale}/patient/bookings`);return{success:'saved'};}
export async function updateBookingAction(_state:JourneyActionState,formData:FormData):Promise<JourneyActionState>{const locale=localeFrom(formData);const context=await requireRoles(locale,[...providerRoles,'PATIENT']);const parsed=bookingUpdateSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:'invalid'};const supabase=await getSupabaseBrowserClient();if(!supabase)return{error:'unavailable'};const v=parsed.data;const patientOnly=context.roles.includes('PATIENT')&&!context.roles.some(role=>providerRoles.includes(role as (typeof providerRoles)[number]));const payload=patientOnly?{status:v.status}:{status:v.status,planned_arrival:emptyToNull(v.planned_arrival),planned_care_date:emptyToNull(v.planned_care_date),estimated_completion:emptyToNull(v.estimated_completion),provider_notes:emptyToNull(v.provider_notes)};const {error}=await supabase.from('bookings').update(payload).eq('id',v.booking_id);if(error)return{error:'save'};revalidatePath(`/${locale}/patient/bookings`);revalidatePath(`/${locale}/provider/bookings`);revalidatePath(`/${locale}/doctor/bookings`);return{success:'saved'};}
