'use client';

import { useActionState, useEffect, useState } from 'react';
import Link from 'next/link';
import { CalendarDays, CheckCircle2, Clock3, Hospital, XCircle } from 'lucide-react';
import { Badge } from '@/src/components/ui/badge';
import { Button } from '@/src/components/ui/button';
import { Card, CardContent } from '@/src/components/ui/card';
import { Input } from '@/src/components/ui/input';
import { Select } from '@/src/components/ui/select';
import { Textarea } from '@/src/components/ui/textarea';
import type { Locale } from '@/src/i18n/config';
import { localized } from '@/src/features/cases/data';
import { decideOfferAction, markOfferViewedAction, saveOfferAction, updateBookingAction, type JourneyActionState } from './actions';
import type { BookingRecord, OfferRecord, ProviderScope } from './data';
import { providerName } from './data';
import type { JourneyDictionary } from './messages';

const initial: JourneyActionState = {};
function Feedback({ state, copy }: { state: JourneyActionState; copy: JourneyDictionary }) { if(state.error)return <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800" role="alert">{copy.common.error}</p>;if(state.success)return <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{copy.common.saved}</p>;return null; }
function StatusBadge({label}:{label:string}){return <Badge variant="blue">{label}</Badge>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-semibold text-slate-800">{label}{children}</label>}

export function OfferForm({ locale, copy, caseId, treatments, doctors, scopes, doctorMode=false, doctorId, record }: { locale:Locale;copy:JourneyDictionary;caseId:string;treatments:Array<{id:string;label:string}>;doctors:Array<{id:string;label:string}>;scopes:ProviderScope[];doctorMode?:boolean;doctorId?:string;record?:OfferRecord }){
  const [state,action,pending]=useActionState(saveOfferAction,initial); const defaultScope=scopes.find(s=>s.entity_id===(record?.hospital_id??record?.pharmacy_id??record?.radiology_center_id??record?.medical_laboratory_id))??scopes[0]; const [scopeKey,setScopeKey]=useState(defaultScope?`${defaultScope.provider_type}:${defaultScope.entity_id}`:''); const scope=scopes.find(s=>`${s.provider_type}:${s.entity_id}`===scopeKey);
  return <form action={action} className="grid gap-5"><input name="locale" type="hidden" value={locale}/><input name="case_id" type="hidden" value={caseId}/>{record?<input name="offer_id" type="hidden" value={record.id}/>:null}<input name="provider_type" type="hidden" value={doctorMode?'DOCTOR':scope?.provider_type??''}/><input name="hospital_id" type="hidden" value={scope?.provider_type==='HOSPITAL'?scope.entity_id:''}/><input name="pharmacy_id" type="hidden" value={scope?.provider_type==='PHARMACY'?scope.entity_id:''}/><input name="radiology_center_id" type="hidden" value={scope?.provider_type==='RADIOLOGY_CENTER'?scope.entity_id:''}/><input name="medical_laboratory_id" type="hidden" value={scope?.provider_type==='MEDICAL_LABORATORY'?scope.entity_id:''}/><Feedback copy={copy} state={state}/>
    {!doctorMode?<Field label={copy.common.provider}><Select onChange={e=>setScopeKey(e.target.value)} required value={scopeKey}>{scopes.map(s=><option key={`${s.provider_type}:${s.entity_id}`} value={`${s.provider_type}:${s.entity_id}`}>{s.label}{s.verified?' ✓':''}</option>)}</Select></Field>:null}
    <input name="recommendation_id" type="hidden" value=""/><Field label={copy.common.doctor}><Select defaultValue={doctorMode?doctorId??'':record?.doctor_id??''} name="doctor_id" required={doctorMode}><option value="">{copy.common.choose}</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</Select></Field>
    <Field label={copy.common.treatment}><Select defaultValue={record?.treatment_id??''} name="treatment_id" required><option value="">{copy.common.choose}</option>{treatments.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</Select></Field>
    <Field label={copy.offers.titleLabel}><Input defaultValue={record?.title} maxLength={180} minLength={3} name="title" required/></Field><Field label={copy.offers.descriptionLabel}><Textarea defaultValue={record?.description} maxLength={8000} minLength={10} name="description" required/></Field>
    <div className="grid gap-5 sm:grid-cols-3"><Field label={copy.offers.cost}><Input defaultValue={record?.estimated_cost} min="0" name="estimated_cost" required step="0.01" type="number"/></Field><Field label={copy.offers.currency}><Input autoCapitalize="characters" defaultValue={record?.currency??''} maxLength={3} minLength={3} name="currency" pattern="[A-Za-z]{3}" placeholder="USD / EUR / EGP" required/></Field><Field label={copy.offers.stay}><Input defaultValue={record?.estimated_stay_days??''} max="365" min="0" name="estimated_stay_days" type="number"/></Field></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field label={copy.offers.startDate}><Input defaultValue={record?.proposed_start_date??''} name="proposed_start_date" type="date"/></Field><Field label={copy.offers.endDate}><Input defaultValue={record?.proposed_end_date??''} name="proposed_end_date" type="date"/></Field></div>
    <div className="grid gap-5 sm:grid-cols-2"><Field label={copy.offers.includes}><Textarea defaultValue={record?.included_services.join('\n')} name="included_services"/><span className="text-xs font-normal text-slate-500">{copy.offers.servicesHint}</span></Field><Field label={copy.offers.excludes}><Textarea defaultValue={record?.excluded_services.join('\n')} name="excluded_services"/></Field></div>
    <Field label={copy.offers.providerNotes}><Textarea defaultValue={record?.provider_notes??''} name="provider_notes"/></Field><Field label={copy.offers.validUntil}><Input defaultValue={record?.valid_until.slice(0,16)} name="valid_until" required type="datetime-local"/></Field><Button loading={pending} type="submit">{copy.common.save}</Button>
  </form>;
}

export function OfferViewedTracker({offerId,locale,enabled}:{offerId:string;locale:Locale;enabled:boolean}){useEffect(()=>{if(enabled)void markOfferViewedAction(offerId,locale)},[enabled,offerId,locale]);return null;}

export function OfferCard({record,locale,copy,href}:{record:OfferRecord;locale:Locale;copy:JourneyDictionary;href:string}){return <Card className="h-full" variant="interactive"><CardContent><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Hospital className="size-5"/></span><StatusBadge label={copy.offers.status[record.status]}/></div><h2 className="mt-4 text-lg font-semibold">{record.title}</h2><p className="mt-2 text-sm text-slate-600">{providerName(record,locale)}</p><p className="mt-4 text-2xl font-bold text-slate-950">{new Intl.NumberFormat(locale,{style:'currency',currency:record.currency}).format(record.estimated_cost)}</p><div className="mt-4 flex flex-wrap gap-3 text-xs text-slate-500"><span>{localized(record.treatment?.name_i18n,locale)}</span>{record.estimated_stay_days!=null?<span>• {record.estimated_stay_days} {copy.offers.days}</span>:null}</div><Link className="mt-5 inline-flex text-sm font-semibold text-blue-700" href={href}>{copy.common.view}</Link></CardContent></Card>}

export function OfferDecisionForm({record,locale,copy}:{record:OfferRecord;locale:Locale;copy:JourneyDictionary}){const [state,action,pending]=useActionState(decideOfferAction,initial);if(!['SENT','VIEWED'].includes(record.status))return record.status==='ACCEPTED'?<p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900">{copy.offers.acceptedNotice}</p>:null;return <form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><input name="offer_id" type="hidden" value={record.id}/><Feedback copy={copy} state={state}/><Field label={copy.offers.decisionNote}><Textarea maxLength={2000} name="decision_note"/></Field><div className="flex flex-wrap gap-3"><Button loading={pending} name="decision" type="submit" value="ACCEPTED"><CheckCircle2 className="size-4"/>{copy.offers.accept}</Button><Button loading={pending} name="decision" type="submit" value="REJECTED" variant="outline"><XCircle className="size-4"/>{copy.offers.reject}</Button></div></form>}

export function BookingCard({record,locale,copy,href}:{record:BookingRecord;locale:Locale;copy:JourneyDictionary;href:string}){return <Link href={href}><Card className="h-full" variant="interactive"><CardContent><div className="flex justify-between gap-3"><span className="font-mono text-sm font-semibold">{record.booking_reference}</span><StatusBadge label={copy.bookings.status[record.status]}/></div><h2 className="mt-4 font-semibold">{record.medical_case?.title}</h2><p className="mt-2 text-sm text-slate-600">{providerName(record,locale)}</p><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="size-4"/>{record.planned_care_date?new Intl.DateTimeFormat(locale).format(new Date(record.planned_care_date)):'—'}</p></CardContent></Card></Link>}

export function BookingUpdateForm({record,locale,copy,patient=false}:{record:BookingRecord;locale:Locale;copy:JourneyDictionary;patient?:boolean}){const [state,action,pending]=useActionState(updateBookingAction,initial);return <form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><input name="booking_id" type="hidden" value={record.id}/><Feedback copy={copy} state={state}/>{patient?<input name="status" type="hidden" value="CANCELLED"/>:<Field label={copy.bookings.updateStatus}><Select defaultValue={record.status} name="status">{Object.entries(copy.bookings.status).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field>}<div className="grid gap-4 sm:grid-cols-3"><Field label={copy.bookings.arrival}><Input defaultValue={record.planned_arrival??''} disabled={patient} name="planned_arrival" type="date"/></Field><Field label={copy.bookings.careDate}><Input defaultValue={record.planned_care_date??''} disabled={patient} name="planned_care_date" type="date"/></Field><Field label={copy.bookings.completion}><Input defaultValue={record.estimated_completion??''} disabled={patient} name="estimated_completion" type="date"/></Field></div><Field label={copy.bookings.providerNotes}><Textarea defaultValue={record.provider_notes??''} disabled={patient} name="provider_notes"/></Field><Button loading={pending} type="submit" variant={patient?'danger':'primary'}>{patient?copy.bookings.status.CANCELLED:copy.common.update}</Button></form>}

export function BookingTimeline({record,locale,copy}:{record:BookingRecord;locale:Locale;copy:JourneyDictionary}){return <ol className="space-y-4">{record.events?.map((event)=><li className="flex gap-3" key={event.id}><span className="mt-1 grid size-8 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-700"><Clock3 className="size-4"/></span><div><p className="text-sm font-semibold">{copy.bookings.status[event.to_status]}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(event.created_at))}</p></div></li>)}</ol>}
