import type { Locale } from '@/src/i18n/config';

const en = {
  common: { back: 'Back', view: 'View details', save: 'Save draft', send: 'Send offer', update: 'Update', empty: 'Nothing here yet', choose: 'Choose an option', required: 'Required', error: 'We could not save your changes.', saved: 'Changes saved.', case: 'Medical case', provider: 'Provider', doctor: 'Doctor', treatment: 'Treatment', date: 'Date', notes: 'Notes' },
  provider: { eyebrow: 'Provider workspace', title: 'Care journey operations', description: 'Manage only the patient cases explicitly assigned to your organization.', cases: 'Accessible cases', draftOffers: 'Draft offers', sentOffers: 'Sent offers', acceptedOffers: 'Accepted offers', activeBookings: 'Active bookings', noScope: 'No active provider organization is linked to this account.', createOffer: 'Prepare offer', recentOffers: 'Recent offers', recentBookings: 'Recent bookings' },
  doctor: { createOffer: 'Prepare medical offer', bookings: 'Upcoming bookings' },
  offers: { eyebrow: 'Medical offers', title: 'My offers', description: 'Compare legitimate care proposals for your medical cases.', providerTitle: 'Offers', providerDescription: 'Prepare, review and send scoped offers.', compare: 'Compare offers', empty: 'No offers are available yet.', titleLabel: 'Offer title', descriptionLabel: 'Description', cost: 'Estimated treatment cost', currency: 'Currency', stay: 'Estimated stay', days: 'days', startDate: 'Proposed start', endDate: 'Proposed end', includes: 'Included services', excludes: 'Excluded services', providerNotes: 'Provider notes', validUntil: 'Valid until', recommendation: 'Recommendation', decisionNote: 'Decision note (optional)', accept: 'Accept offer', reject: 'Reject offer', withdraw: 'Withdraw offer', locked: 'Sent offer contents are locked.', acceptedNotice: 'This offer has been accepted and a booking was created.', verification: 'Verified provider', servicesHint: 'Enter one service per line.', status: { DRAFT: 'Draft', SENT: 'Sent', VIEWED: 'Viewed', ACCEPTED: 'Accepted', REJECTED: 'Rejected', EXPIRED: 'Expired', WITHDRAWN: 'Withdrawn' } },
  bookings: { eyebrow: 'Care journey', title: 'My bookings', description: 'Track confirmed care arrangements created from accepted offers.', providerTitle: 'Bookings', providerDescription: 'Coordinate the internal CareBridge booking lifecycle.', empty: 'No bookings are available yet.', reference: 'Booking reference', arrival: 'Planned arrival', careDate: 'Consultation / admission', completion: 'Estimated completion', patientNotes: 'Patient notes', providerNotes: 'Provider notes', timeline: 'Booking timeline', relatedOffer: 'Related offer', relatedCase: 'Related medical case', updateStatus: 'Update booking status', status: { PENDING_CONFIRMATION: 'Pending confirmation', CONFIRMED: 'Confirmed', SCHEDULED: 'Scheduled', IN_PROGRESS: 'In progress', COMPLETED: 'Completed', CANCELLED: 'Cancelled' } },
  notifications: { offerSentTitle: 'New medical offer', offerSentMessage: 'A provider sent a new offer for your case.', offerViewedTitle: 'Offer viewed', offerViewedMessage: 'The patient viewed your offer.', offerAcceptedTitle: 'Offer accepted', offerAcceptedMessage: 'The patient accepted your offer.', offerRejectedTitle: 'Offer rejected', offerRejectedMessage: 'The patient declined your offer.', bookingCreatedTitle: 'Booking created', bookingCreatedMessage: 'A care journey booking was created from the accepted offer.', bookingStatusTitle: 'Booking updated', bookingStatusMessage: 'The status of your care journey booking changed.' },
};

type DeepString<T> = T extends string ? string : { [K in keyof T]: DeepString<T[K]> };
export type JourneyDictionary = DeepString<typeof en>;

const fr: JourneyDictionary = {
  common: { back: 'Retour', view: 'Voir les détails', save: 'Enregistrer le brouillon', send: 'Envoyer l’offre', update: 'Mettre à jour', empty: 'Aucun élément pour le moment', choose: 'Choisir une option', required: 'Obligatoire', error: 'Impossible d’enregistrer vos modifications.', saved: 'Modifications enregistrées.', case: 'Dossier médical', provider: 'Prestataire', doctor: 'Médecin', treatment: 'Traitement', date: 'Date', notes: 'Notes' },
  provider: { eyebrow: 'Espace prestataire', title: 'Opérations du parcours de soins', description: 'Gérez uniquement les dossiers explicitement attribués à votre organisation.', cases: 'Dossiers accessibles', draftOffers: 'Offres en brouillon', sentOffers: 'Offres envoyées', acceptedOffers: 'Offres acceptées', activeBookings: 'Réservations actives', noScope: 'Aucune organisation prestataire active n’est liée à ce compte.', createOffer: 'Préparer une offre', recentOffers: 'Offres récentes', recentBookings: 'Réservations récentes' },
  doctor: { createOffer: 'Préparer une offre médicale', bookings: 'Réservations à venir' },
  offers: { eyebrow: 'Offres médicales', title: 'Mes offres', description: 'Comparez les propositions de soins légitimes liées à vos dossiers médicaux.', providerTitle: 'Offres', providerDescription: 'Préparez, vérifiez et envoyez des offres limitées à votre périmètre.', compare: 'Comparer les offres', empty: 'Aucune offre disponible.', titleLabel: 'Titre de l’offre', descriptionLabel: 'Description', cost: 'Coût estimé du traitement', currency: 'Devise', stay: 'Séjour estimé', days: 'jours', startDate: 'Début proposé', endDate: 'Fin proposée', includes: 'Services inclus', excludes: 'Services exclus', providerNotes: 'Notes du prestataire', validUntil: 'Valable jusqu’au', recommendation: 'Recommandation', decisionNote: 'Note de décision (facultative)', accept: 'Accepter l’offre', reject: 'Refuser l’offre', withdraw: 'Retirer l’offre', locked: 'Le contenu d’une offre envoyée est verrouillé.', acceptedNotice: 'Cette offre a été acceptée et une réservation a été créée.', verification: 'Prestataire vérifié', servicesHint: 'Saisissez un service par ligne.', status: { DRAFT: 'Brouillon', SENT: 'Envoyée', VIEWED: 'Consultée', ACCEPTED: 'Acceptée', REJECTED: 'Refusée', EXPIRED: 'Expirée', WITHDRAWN: 'Retirée' } },
  bookings: { eyebrow: 'Parcours de soins', title: 'Mes réservations', description: 'Suivez les soins organisés à partir des offres acceptées.', providerTitle: 'Réservations', providerDescription: 'Coordonnez le cycle interne des réservations CareBridge.', empty: 'Aucune réservation disponible.', reference: 'Référence', arrival: 'Arrivée prévue', careDate: 'Consultation / admission', completion: 'Fin estimée', patientNotes: 'Notes du patient', providerNotes: 'Notes du prestataire', timeline: 'Chronologie', relatedOffer: 'Offre associée', relatedCase: 'Dossier associé', updateStatus: 'Mettre à jour le statut', status: { PENDING_CONFIRMATION: 'En attente de confirmation', CONFIRMED: 'Confirmée', SCHEDULED: 'Planifiée', IN_PROGRESS: 'En cours', COMPLETED: 'Terminée', CANCELLED: 'Annulée' } },
  notifications: { offerSentTitle: 'Nouvelle offre médicale', offerSentMessage: 'Un prestataire a envoyé une nouvelle offre pour votre dossier.', offerViewedTitle: 'Offre consultée', offerViewedMessage: 'Le patient a consulté votre offre.', offerAcceptedTitle: 'Offre acceptée', offerAcceptedMessage: 'Le patient a accepté votre offre.', offerRejectedTitle: 'Offre refusée', offerRejectedMessage: 'Le patient a refusé votre offre.', bookingCreatedTitle: 'Réservation créée', bookingCreatedMessage: 'Une réservation a été créée depuis l’offre acceptée.', bookingStatusTitle: 'Réservation mise à jour', bookingStatusMessage: 'Le statut de votre parcours de soins a changé.' },
};

const ar: JourneyDictionary = {
  common: { back: 'رجوع', view: 'عرض التفاصيل', save: 'حفظ المسودة', send: 'إرسال العرض', update: 'تحديث', empty: 'لا توجد بيانات بعد', choose: 'اختر', required: 'مطلوب', error: 'تعذر حفظ التغييرات.', saved: 'تم حفظ التغييرات.', case: 'الحالة الطبية', provider: 'مقدم الرعاية', doctor: 'الطبيب', treatment: 'العلاج', date: 'التاريخ', notes: 'ملاحظات' },
  provider: { eyebrow: 'مساحة مقدم الرعاية', title: 'إدارة رحلة الرعاية', description: 'إدارة الحالات المعينة صراحةً لمؤسستك فقط.', cases: 'الحالات المتاحة', draftOffers: 'مسودات العروض', sentOffers: 'العروض المرسلة', acceptedOffers: 'العروض المقبولة', activeBookings: 'الحجوزات النشطة', noScope: 'لا توجد مؤسسة رعاية نشطة مرتبطة بهذا الحساب.', createOffer: 'إعداد عرض', recentOffers: 'العروض الحديثة', recentBookings: 'الحجوزات الحديثة' },
  doctor: { createOffer: 'إعداد عرض طبي', bookings: 'الحجوزات القادمة' },
  offers: { eyebrow: 'العروض الطبية', title: 'عروضي', description: 'قارن عروض الرعاية المرتبطة بحالاتك الطبية.', providerTitle: 'العروض', providerDescription: 'إعداد ومراجعة وإرسال العروض ضمن نطاق الصلاحية.', compare: 'مقارنة العروض', empty: 'لا توجد عروض متاحة بعد.', titleLabel: 'عنوان العرض', descriptionLabel: 'الوصف', cost: 'تكلفة العلاج التقديرية', currency: 'العملة', stay: 'الإقامة التقديرية', days: 'أيام', startDate: 'تاريخ البدء المقترح', endDate: 'تاريخ الانتهاء المقترح', includes: 'الخدمات المشمولة', excludes: 'الخدمات غير المشمولة', providerNotes: 'ملاحظات مقدم الرعاية', validUntil: 'صالح حتى', recommendation: 'التوصية', decisionNote: 'ملاحظة القرار (اختيارية)', accept: 'قبول العرض', reject: 'رفض العرض', withdraw: 'سحب العرض', locked: 'محتوى العرض المرسل مقفل.', acceptedNotice: 'تم قبول العرض وإنشاء حجز.', verification: 'مقدم رعاية موثّق', servicesHint: 'أدخل خدمة واحدة في كل سطر.', status: { DRAFT: 'مسودة', SENT: 'مرسل', VIEWED: 'تمت المشاهدة', ACCEPTED: 'مقبول', REJECTED: 'مرفوض', EXPIRED: 'منتهي', WITHDRAWN: 'مسحوب' } },
  bookings: { eyebrow: 'رحلة الرعاية', title: 'حجوزاتي', description: 'تابع ترتيبات الرعاية الناتجة عن العروض المقبولة.', providerTitle: 'الحجوزات', providerDescription: 'تنسيق دورة الحجز الداخلية في CareBridge.', empty: 'لا توجد حجوزات بعد.', reference: 'مرجع الحجز', arrival: 'الوصول المخطط', careDate: 'الاستشارة / الدخول', completion: 'الانتهاء التقديري', patientNotes: 'ملاحظات المريض', providerNotes: 'ملاحظات مقدم الرعاية', timeline: 'الخط الزمني للحجز', relatedOffer: 'العرض المرتبط', relatedCase: 'الحالة المرتبطة', updateStatus: 'تحديث حالة الحجز', status: { PENDING_CONFIRMATION: 'بانتظار التأكيد', CONFIRMED: 'مؤكد', SCHEDULED: 'مجدول', IN_PROGRESS: 'قيد التنفيذ', COMPLETED: 'مكتمل', CANCELLED: 'ملغي' } },
  notifications: { offerSentTitle: 'عرض طبي جديد', offerSentMessage: 'أرسل مقدم رعاية عرضاً جديداً لحالتك.', offerViewedTitle: 'تمت مشاهدة العرض', offerViewedMessage: 'شاهد المريض عرضك.', offerAcceptedTitle: 'تم قبول العرض', offerAcceptedMessage: 'قبل المريض عرضك.', offerRejectedTitle: 'تم رفض العرض', offerRejectedMessage: 'رفض المريض عرضك.', bookingCreatedTitle: 'تم إنشاء الحجز', bookingCreatedMessage: 'تم إنشاء حجز رحلة رعاية من العرض المقبول.', bookingStatusTitle: 'تم تحديث الحجز', bookingStatusMessage: 'تغيرت حالة حجز رحلة الرعاية.' },
};

export function getJourneyDictionary(locale: Locale): JourneyDictionary { return locale === 'fr' ? fr : locale === 'ar' ? ar : en; }
