import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import{getPatientJourneyDictionary}from'@/src/features/patient-journey/messages';
const migration=readFileSync('supabase/migrations/202609050001_patient_journey_portal.sql','utf8');const ui=readFileSync('src/features/patient-journey/patient-journey-ui.tsx','utf8');
describe('Patient Journey Portal Phase 2',()=>{
 it('allows only assigned patient hospital selection through a secure RPC',()=>{expect(migration).toContain("service.selection_state<>'PATIENT_TO_CHOOSE'");expect(migration).toContain('journey.patient_id<>auth.uid()');expect(migration).toContain('patient selections must use the secure journey selection workflow');});
 it('snapshots the configured hospital price and currency without a USD assumption',()=>{expect(migration).toContain('ht.starting_price,ht.currency');expect(migration).toContain('selected_price=option_price,currency=option_currency');expect(ui).toContain("new Intl.NumberFormat(locale,{style:'currency',currency})");expect(ui).not.toContain("'$'");});
 it('prevents duplicate confirmed provider and accommodation choices',()=>{expect(migration).toContain('a clinical provider is already confirmed');expect(migration).toContain('accommodation already arranged');expect(migration).toContain("p.arrangement='PATIENT_WILL_CHOOSE'");});
 it('returns only safe completed encounter summaries and excludes private notes',()=>{const start=migration.indexOf('create function public.get_patient_journey_encounter_history');const end=migration.indexOf('create or replace function public.reserve_accommodation');const fn=migration.slice(start,end);expect(fn).toContain("e.status='COMPLETED'");expect(fn).not.toContain('clinical_notes');});
 it('provides natural Arabic journey copy',()=>{const copy=getPatientJourneyDictionary('ar');expect(copy.title).toBe('رحلة علاجي');expect(copy.patientChoice).toBe('بانتظار اختيارك');expect(copy.payments).toBe('المدفوعات');});
 it('contains all requested journey sections',()=>{for(const id of ['clinical','schedule','accommodation','travel','payments','medical-history','documents','notifications'])expect(ui).toContain(`id="${id}"`);});
});
