import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, FilePlus2 } from 'lucide-react';
import { Badge } from '@/src/components/ui/badge';
import { Card, CardContent, CardHeader } from '@/src/components/ui/card';
import { RecommendationForm } from '@/src/features/cases/case-forms';
import { loadDoctorCase, localized } from '@/src/features/cases/data';
import { getCaseDictionary } from '@/src/features/cases/messages';
import { getJourneyDictionary } from '@/src/features/journey/messages';
import { isLocale } from '@/src/i18n/config';
import { requireRoles } from '@/src/lib/auth/context';
import { getSupabaseServerClient } from '@/src/lib/supabase/server';

export const dynamic = 'force-dynamic';
export default async function DoctorCasePage({ params }: { params: Promise<{ locale: string; caseId: string }> }) { const { locale, caseId } = await params; if (!isLocale(locale)) notFound(); const context = await requireRoles(locale, ['DOCTOR']); const supabase = await getSupabaseServerClient(); if (!supabase) notFound(); const copy = getCaseDictionary(locale); const journeyCopy = getJourneyDictionary(locale); const detail = await loadDoctorCase(supabase, context.userId, caseId, locale); if (!detail.record || !detail.doctor) notFound(); const record = detail.record; return <div className="mx-auto max-w-6xl"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-blue-700" href={`/${locale}/doctor`}><ArrowLeft className="size-4 rtl:rotate-180" />{copy.case.back}</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm font-semibold uppercase tracking-widest text-blue-700">{copy.doctor.review}</p><h1 className="mt-2 text-3xl font-bold">{record.title}</h1><p className="mt-2 text-slate-600">{localized(record.specialty?.name_i18n, locale)}</p></div><div className="flex items-center gap-3"><Badge variant="blue">{copy.statuses[record.status]}</Badge><Link className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-blue-700 px-4 text-sm font-semibold text-white" href={`/${locale}/doctor/cases/${caseId}/offer`}><FilePlus2 className="size-4"/>{journeyCopy.doctor.createOffer}</Link></div></div><div className="mt-8 grid gap-6 xl:grid-cols-2"><Card><CardHeader><h2 className="text-lg font-semibold">{copy.case.editTitle}</h2></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{record.description}</p>{record.symptoms_notes ? <p className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6">{record.symptoms_notes}</p> : null}<h3 className="mt-7 font-semibold">{copy.documents.title}</h3><div className="mt-3 grid gap-2">{detail.documents.map((document) => document.signedUrl ? <a className="rounded-xl border border-slate-200 p-3 text-sm font-semibold text-blue-700" href={document.signedUrl} key={document.id} rel="noreferrer" target="_blank">{document.original_filename}</a> : null)}{detail.documents.length === 0 ? <p className="text-sm text-slate-500">{copy.documents.empty}</p> : null}</div></CardContent></Card><Card variant="form"><CardHeader><h2 className="text-lg font-semibold">{copy.recommendation.title}</h2></CardHeader><CardContent><RecommendationForm caseId={caseId} copy={copy} locale={locale} recommendation={detail.recommendation} treatments={detail.treatments} /></CardContent></Card></div></div>; }
