import Link from 'next/link';
import {notFound} from 'next/navigation';
import {CalendarClock,FilePlus2,HeartPulse,Search,Stethoscope,WalletCards} from 'lucide-react';
import {Badge} from '@/src/components/ui/badge';
import {Card,CardContent} from '@/src/components/ui/card';
import {EmptyState} from '@/src/components/ui/empty-state';
import {PageHeader} from '@/src/components/ui/page-header';
import {StatCard} from '@/src/components/ui/stat-card';
import {getCaseDictionary} from '@/src/features/cases/messages';
import {loadPatientCases,localized} from '@/src/features/cases/data';
import {loadBookings,loadOffers} from '@/src/features/journey/data';
import {isLocale} from '@/src/i18n/config';
import {requireRoles} from '@/src/lib/auth/context';
import {getSupabaseServerClient} from '@/src/lib/supabase/server';
export const dynamic='force-dynamic';

export default async function Page({params}:{params:Promise<{locale:string}>}){
 const{locale}=await params;if(!isLocale(locale))notFound();const context=await requireRoles(locale,['PATIENT']);const copy=getCaseDictionary(locale);const s=await getSupabaseServerClient();
 const[cases,bookings,offers,appointments,invoices]=s?await Promise.all([loadPatientCases(s,context.userId),loadBookings(s),loadOffers(s),s.from('appointments').select('id,scheduled_at,status').gte('scheduled_at',new Date().toISOString()).not('status','in','(CANCELLED,COMPLETED,NO_SHOW)').order('scheduled_at').limit(1),s.from('invoices').select('currency,total_amount,amount_paid,status,created_at').order('created_at',{ascending:false}).limit(1)]):[[],[],[],{data:[]},{data:[]}];
 const activeBooking=bookings.find(item=>!['COMPLETED','CANCELLED'].includes(item.status));const newOffers=offers.filter(item=>['SENT','VIEWED'].includes(item.status)).length;const next=appointments.data?.[0];const invoice=invoices.data?.[0];const finance=invoice?invoice.status==='PAID'?(locale==='ar'?'مسددة':locale==='fr'?'Payée':'Paid'):new Intl.NumberFormat(locale,{style:'currency',currency:invoice.currency}).format(Math.max(0,invoice.total_amount-invoice.amount_paid)):'—';
 return <div className="mx-auto max-w-7xl"><PageHeader description={copy.patient.description} eyebrow={copy.patient.eyebrow} title={copy.patient.title}/><div className="mt-6 flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-blue-700 px-5 text-sm font-semibold text-white" href={`/${locale}/patient/cases/new`}><FilePlus2 className="size-4"/>{copy.patient.create}</Link><Link className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 text-sm font-semibold" href={`/${locale}/patient/providers`}><Search className="size-4"/>{copy.patient.browse}</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard hint={activeBooking?.booking_reference??(locale==='ar'?'لا توجد رحلة علاج نشطة':locale==='fr'?'Aucun parcours actif':'No active journey')} icon={HeartPulse} title={locale==='ar'?'رحلة العلاج الحالية':locale==='fr'?'Parcours en cours':'Current care journey'} value={activeBooking?(locale==='ar'?'نشطة':locale==='fr'?'Active':'Active'):'—'}/><StatCard hint={next?new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(next.scheduled_at)):(locale==='ar'?'لا توجد مواعيد قادمة':locale==='fr'?'Aucun rendez-vous à venir':'No upcoming appointments')} icon={CalendarClock} title={locale==='ar'?'الموعد القادم':locale==='fr'?'Prochain rendez-vous':'Next appointment'} value={next?'1':'0'}/><StatCard hint={locale==='ar'?'عروض جديدة بانتظار قرارك':locale==='fr'?'Nouvelles offres à examiner':'New offers awaiting your review'} icon={Stethoscope} title={locale==='ar'?'العروض الطبية الجديدة':locale==='fr'?'Nouvelles offres':'New medical offers'} tone="violet" value={String(newOffers)}/><StatCard hint={invoice?invoice.currency:(locale==='ar'?'لا توجد فواتير':locale==='fr'?'Aucune facture':'No invoices')} icon={WalletCards} title={locale==='ar'?'الحالة المالية':locale==='fr'?'Situation financière':'Financial status'} tone="emerald" value={finance}/></div><section className="mt-8"><h2 className="text-lg font-semibold">{copy.patient.recent}</h2>{cases.length?<div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{cases.map(record=><Link href={`/${locale}/patient/cases/${record.id}`} key={record.id}><Card className="h-full" variant="interactive"><CardContent><div className="flex items-center justify-between gap-3"><Badge variant="blue">{copy.statuses[record.status]}</Badge><Stethoscope className="size-5 text-slate-400"/></div><h3 className="mt-4 font-semibold">{record.title}</h3><p className="mt-2 text-sm text-slate-600">{localized(record.specialty?.name_i18n,locale)}</p><p className="mt-5 text-xs text-slate-500">{copy.case.updated}: {new Intl.DateTimeFormat(locale).format(new Date(record.updated_at))}</p></CardContent></Card></Link>)}</div>:<div className="mt-4"><EmptyState description={copy.patient.emptyDescription} title={copy.patient.empty}/></div>}</section></div>
}
