import{revalidatePath}from'@/src/react-app/compat/cache';import{isLocale,type Locale}from'@/src/i18n/config';import{requireRoles}from'@/src/lib/auth/context';import{getSupabaseBrowserClient}from'@/src/lib/supabase/browser';import{zonedLocalDateTimeToIso}from'@/src/lib/datetime/timezone';import{z}from'zod';
export interface DoctorProgramState{error?:'invalid'|'save';success?:'saved'}
const uuid=z.string().uuid(),text=(min:number,max:number)=>z.string().trim().min(min).max(max);
const recommendationSchema=z.object({locale:z.string(),booking_id:uuid,treatment_id:uuid,recommendation_notes:text(10,8000),next_steps:z.string().trim().max(4000).optional()});
const procedureSchema=z.object({locale:z.string(),booking_id:uuid,appointment_id:z.union([uuid,z.literal('')]).optional(),hospital_id:uuid,treatment_id:uuid,scheduled_at:z.string().min(1),timezone:text(1,80),duration_minutes:z.coerce.number().int().min(5).max(720),location_name:text(2,300),instructions:z.string().trim().max(4000).optional(),confirm:z.enum(['yes','no'])});
const localeOf=(value:string):Locale=>isLocale(value)?value:'en';
function refresh(locale:Locale,id:string){revalidatePath(`/${locale}/doctor/bookings/${id}`);revalidatePath(`/${locale}/doctor/clinical`);revalidatePath(`/${locale}/patient/journeys/${id}`)}
export async function recommendTreatmentAction(_:DoctorProgramState,f:FormData):Promise<DoctorProgramState>{const p=recommendationSchema.safeParse(Object.fromEntries(f)),locale=localeOf(String(f.get('locale')??'en'));await requireRoles(locale,['DOCTOR']);if(!p.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'save'};const v=p.data,{error}=await s.rpc('doctor_recommend_journey_treatment',{target_booking_id:v.booking_id,target_treatment_id:v.treatment_id,target_notes:v.recommendation_notes,target_next_steps:v.next_steps||null});if(error)return{error:'save'};refresh(locale,v.booking_id);return{success:'saved'}}
export async function saveProcedureAction(_:DoctorProgramState,f:FormData):Promise<DoctorProgramState>{const p=procedureSchema.safeParse(Object.fromEntries(f)),locale=localeOf(String(f.get('locale')??'en'));await requireRoles(locale,['DOCTOR']);if(!p.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'save'};const v=p.data;let scheduledAt:string;try{scheduledAt=zonedLocalDateTimeToIso(v.scheduled_at,v.timezone)}catch{return{error:'invalid'}}const{error}=await s.rpc('doctor_save_journey_procedure',{target_booking_id:v.booking_id,target_hospital_id:v.hospital_id,target_treatment_id:v.treatment_id,target_scheduled_at:scheduledAt,target_timezone:v.timezone,target_duration_minutes:v.duration_minutes,target_location_name:v.location_name,target_instructions:v.instructions||null,target_confirm:v.confirm==='yes',target_appointment_id:v.appointment_id||null});if(error)return{error:'save'};refresh(locale,v.booking_id);return{success:'saved'}}
