import {redirect} from '@/src/react-app/compat/navigation';
import {revalidatePath} from '@/src/react-app/compat/cache';
import type {Locale} from '@/src/i18n/config';
import {isLocale} from '@/src/i18n/config';
import {requireRoles} from '@/src/lib/auth/context';
import {getSupabaseBrowserClient} from '@/src/lib/supabase/browser';
import {clinicalFileSchema,encounterSchema,followUpSchema,journeyStatusSchema,orderSchema,orderStatusSchema,prescriptionSchema,resultSchema} from './validation';

const randomUUID=()=>crypto.randomUUID();

export type ClinicalActionState={error?:'invalid'|'unauthorized'|'save'|'upload'|'unavailable';success?:string};
const nil=(v:string|undefined|null)=>v||null;
function localeOf(f:FormData):Locale{const v=String(f.get('locale')??'en');return isLocale(v)?v:'en';}
function refresh(locale:Locale,id:string){for(const portal of ['patient','doctor'])revalidatePath(`/${locale}/${portal}/bookings/${id}`);revalidatePath(`/${locale}/patient/journeys/${id}`);revalidatePath(`/${locale}/doctor/clinical`);revalidatePath(`/${locale}/provider/diagnostics`);}
async function doctorContext(locale:Locale,bookingId:string){const auth=await requireRoles(locale,['DOCTOR']);const s=await getSupabaseBrowserClient();if(!s)return null;const[{data:booking},{data:doctor}]=await Promise.all([s.from('bookings').select('id,case_id,patient_id,doctor_id').eq('id',bookingId).maybeSingle(),s.from('doctors').select('id').eq('user_id',auth.userId).eq('status','ACTIVE').eq('verification_state','VERIFIED').maybeSingle()]);if(!booking||!doctor)return null;const assigned=booking.doctor_id===doctor.id||(await s.from('journey_services').select('id').eq('booking_id',bookingId).eq('doctor_id',doctor.id).eq('service_type','DOCTOR_CONSULTATION').not('status','in','(CANCELLED,ARCHIVED)').limit(1)).data?.length;if(!assigned)return null;return{s,auth,booking,doctorId:doctor.id};}

export async function createEncounterAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f),p=encounterSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const c=await doctorContext(locale,p.data.booking_id);if(!c)return{error:'unauthorized'};const v=p.data;const{error}=await c.s.from('clinical_encounters').insert({booking_id:c.booking.id,case_id:c.booking.case_id,patient_id:c.booking.patient_id,doctor_id:c.doctorId,appointment_id:nil(v.appointment_id),encountered_at:new Date(v.encountered_at).toISOString(),clinical_notes:v.clinical_notes,assessment:v.assessment,diagnosis_summary:v.diagnosis_summary,treatment_progress:v.treatment_progress,next_steps:v.next_steps,follow_up_recommendation:v.follow_up_recommendation,status:v.status,created_by:c.auth.userId});if(error)return{error:'save'};refresh(locale,c.booking.id);return{success:'saved'};}

export async function updateEncounterAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f),id=String(f.get('encounter_id')??''),p=encounterSchema.safeParse(Object.fromEntries(f));if(!id||!p.success)return{error:'invalid'};const c=await doctorContext(locale,p.data.booking_id);if(!c)return{error:'unauthorized'};const v=p.data;const{error}=await c.s.from('clinical_encounters').update({appointment_id:nil(v.appointment_id),encountered_at:new Date(v.encountered_at).toISOString(),clinical_notes:v.clinical_notes,assessment:v.assessment,diagnosis_summary:v.diagnosis_summary,treatment_progress:v.treatment_progress,next_steps:v.next_steps,follow_up_recommendation:v.follow_up_recommendation,status:v.status}).eq('id',id).eq('booking_id',c.booking.id).eq('status','OPEN');if(error)return{error:'save'};refresh(locale,c.booking.id);return{success:'saved'};}

export async function deleteDraftClinicalAction(f:FormData){const locale=localeOf(f),bookingId=String(f.get('booking_id')??''),id=String(f.get('record_id')??''),kind=String(f.get('kind')??'');const tables={encounter:'clinical_encounters',prescription:'prescriptions',lab:'lab_orders',radiology:'radiology_orders',follow_up:'clinical_follow_ups'}as const;if(!id||!(kind in tables))return;const c=await doctorContext(locale,bookingId);if(!c)return;await c.s.from(tables[kind as keyof typeof tables]).delete().eq('id',id).eq('booking_id',bookingId);refresh(locale,bookingId);}

export async function createPrescriptionAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f),p=prescriptionSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const c=await doctorContext(locale,p.data.booking_id);if(!c)return{error:'unauthorized'};const v=p.data;const{data:rx,error}=await c.s.from('prescriptions').insert({booking_id:c.booking.id,case_id:c.booking.case_id,patient_id:c.booking.patient_id,doctor_id:c.doctorId,appointment_id:nil(v.appointment_id),instructions:v.instructions,notes:v.notes,created_by:c.auth.userId}).select('id').single();if(error||!rx)return{error:'save'};const item=await c.s.from('prescription_items').insert({prescription_id:rx.id,medication_name:v.medication_name,strength:v.strength,dosage:v.dosage,frequency:v.frequency,route:v.route,duration:v.duration,instructions:v.item_instructions});if(item.error)return{error:'save'};refresh(locale,c.booking.id);return{success:'saved'};}
export async function issuePrescriptionAction(f:FormData){const locale=localeOf(f),bookingId=String(f.get('booking_id')??''),id=String(f.get('prescription_id')??'');const c=await doctorContext(locale,bookingId);if(c&&id)await c.s.from('prescriptions').update({status:'ISSUED'}).eq('id',id).eq('booking_id',bookingId);refresh(locale,bookingId);}

export async function createOrderAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f),kind=String(f.get('kind')),p=orderSchema.safeParse(Object.fromEntries(f));if(!p.success||!['lab','radiology'].includes(kind))return{error:'invalid'};const c=await doctorContext(locale,p.data.booking_id);if(!c)return{error:'unauthorized'};const v=p.data,base={booking_id:c.booking.id,case_id:c.booking.case_id,patient_id:c.booking.patient_id,doctor_id:c.doctorId,appointment_id:nil(v.appointment_id),encounter_id:nil(v.encounter_id),priority:v.priority,clinical_instructions:v.clinical_instructions,created_by:c.auth.userId};if(kind==='lab'){const{data,error}=await c.s.from('lab_orders').insert({...base,medical_laboratory_id:v.provider_id}).select('id').single();if(error||!data)return{error:'save'};if((await c.s.from('lab_order_tests').insert({lab_order_id:data.id,test_name:v.requested_name})).error)return{error:'save'};}else if((await c.s.from('radiology_orders').insert({...base,radiology_center_id:v.provider_id,study_name:v.requested_name,modality:v.modality,body_area:v.body_area})).error)return{error:'save'};refresh(locale,c.booking.id);return{success:'saved'};}

export async function createFollowUpAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f),p=followUpSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const c=await doctorContext(locale,p.data.booking_id);if(!c)return{error:'unauthorized'};const v=p.data;const{error}=await c.s.from('clinical_follow_ups').insert({booking_id:c.booking.id,patient_id:c.booking.patient_id,doctor_id:c.doctorId,encounter_id:nil(v.encounter_id),appointment_id:nil(v.appointment_id),recommended_date:nil(v.recommended_date),window_end_date:nil(v.window_end_date),recommendation:v.recommendation,status:v.appointment_id?'SCHEDULED':'PLANNED',created_by:c.auth.userId});if(error)return{error:'save'};refresh(locale,c.booking.id);return{success:'saved'};}
export async function updateFollowUpAction(f:FormData){const locale=localeOf(f),bookingId=String(f.get('booking_id')??''),id=String(f.get('follow_up_id')??''),status=String(f.get('status')??'');if(!['SCHEDULED','COMPLETED','CANCELLED'].includes(status))return;const c=await doctorContext(locale,bookingId);if(!c||!id)return;await c.s.from('clinical_follow_ups').update({status}).eq('id',id).eq('booking_id',bookingId);refresh(locale,bookingId);}
export async function updateJourneyStatusAction(f:FormData){const locale=localeOf(f),p=journeyStatusSchema.safeParse(Object.fromEntries(f));if(!p.success)return;const c=await doctorContext(locale,p.data.booking_id);if(!c)return;await c.s.from('bookings').update({clinical_status:p.data.status}).eq('id',p.data.booking_id);refresh(locale,p.data.booking_id);}

export async function updateDiagnosticOrderAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f);await requireRoles(locale,['PROVIDER','HOSPITAL_ADMIN','HOSPITAL_COORDINATOR','ADMIN','SUPER_ADMIN']);const p=orderStatusSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const allowed=p.data.kind==='lab'?['SCHEDULED','SAMPLE_COLLECTED','IN_PROGRESS','RESULT_AVAILABLE','CANCELLED']:['SCHEDULED','IN_PROGRESS','RESULT_AVAILABLE','CANCELLED'];if(!allowed.includes(p.data.status))return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'unavailable'};const table=p.data.kind==='lab'?'lab_orders':'radiology_orders';const{data,error}=await s.from(table).update({status:p.data.status}).eq('id',p.data.order_id).select('booking_id').maybeSingle();if(error||!data)return{error:'save'};refresh(locale,data.booking_id);return{success:'saved'};}
export async function saveDiagnosticResultAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PROVIDER','HOSPITAL_ADMIN','HOSPITAL_COORDINATOR','ADMIN','SUPER_ADMIN']);const p=resultSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'unavailable'};const v=p.data,orderTable=v.kind==='lab'?'lab_orders':'radiology_orders',resultTable=v.kind==='lab'?'lab_results':'radiology_results',orderKey=v.kind==='lab'?'lab_order_id':'radiology_order_id',notesKey=v.kind==='lab'?'result_notes':'report_notes';const{data:order}=await s.from(orderTable).select('id,booking_id,patient_id').eq('id',v.order_id).maybeSingle();if(!order)return{error:'unauthorized'};const{data:existing}=await s.from(resultTable).select('id').eq(orderKey,v.order_id).maybeSingle();const payload={summary:v.summary,[notesKey]:v.notes,...(v.release==='yes'?{released_at:new Date().toISOString()}: {})};const result=existing?await s.from(resultTable).update(payload).eq('id',existing.id):await s.from(resultTable).insert({...payload,[orderKey]:v.order_id,patient_id:order.patient_id,created_by:auth.userId});if(result.error)return{error:'save'};refresh(locale,order.booking_id);return{success:'saved'};}
export async function reviewResultAction(f:FormData){const locale=localeOf(f),bookingId=String(f.get('booking_id')??''),kind=String(f.get('kind')),id=String(f.get('result_id')??'');const c=await doctorContext(locale,bookingId);if(!c||!id||!['lab','radiology'].includes(kind))return;await c.s.from(kind==='lab'?'lab_results':'radiology_results').update({reviewed_at:new Date().toISOString()}).eq('id',id);refresh(locale,bookingId);}

export async function uploadClinicalResultAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PROVIDER','HOSPITAL_ADMIN','HOSPITAL_COORDINATOR','ADMIN','SUPER_ADMIN']);const kind=String(f.get('kind')),resultId=String(f.get('result_id')??''),file=clinicalFileSchema.safeParse(f.get('document'));if(!file.success||!['lab','radiology'].includes(kind)||!resultId)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'unavailable'};const resultTable=kind==='lab'?'lab_results':'radiology_results';const{data:result}=await s.from(resultTable).select('patient_id').eq('id',resultId).maybeSingle();if(!result)return{error:'unauthorized'};const safe=file.data.name.replace(/[^A-Za-z0-9._-]/g,'_').slice(-160)||'result';const path=`${result.patient_id}/${kind}/${resultId}/${randomUUID()}-${safe}`;const uploaded=await s.storage.from('clinical-results').upload(path,file.data,{contentType:file.data.type,upsert:false});if(uploaded.error)return{error:'upload'};const metadata=await s.from('clinical_result_documents').insert({[kind==='lab'?'lab_result_id':'radiology_result_id']:resultId,patient_id:result.patient_id,object_path:path,original_filename:file.data.name.slice(0,240),mime_type:file.data.type,file_size_bytes:file.data.size,uploaded_by:auth.userId});if(metadata.error){await s.storage.from('clinical-results').remove([path]);return{error:'save'};}revalidatePath(`/${locale}/provider/diagnostics`);return{success:'saved'};}
export async function downloadClinicalDocumentAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,['PATIENT','DOCTOR','PROVIDER','ADMIN','SUPER_ADMIN']);const path=String(f.get('path')??'');if(!path)return;const s=await getSupabaseBrowserClient();if(!s)return;const{data}=await s.storage.from('clinical-results').createSignedUrl(path,60);if(data?.signedUrl)redirect(data.signedUrl);}

export async function uploadClinicalAttachmentAction(_:ClinicalActionState,f:FormData):Promise<ClinicalActionState>{const locale=localeOf(f),bookingId=String(f.get('booking_id')??''),title=String(f.get('title')??'').trim(),encounterId=nil(String(f.get('encounter_id')??'')),appointmentId=nil(String(f.get('appointment_id')??'')),file=clinicalFileSchema.safeParse(f.get('document'));if(!file.success||file.data.size>15728640||title.length<2||title.length>180)return{error:'invalid'};const c=await doctorContext(locale,bookingId);if(!c)return{error:'unauthorized'};const safe=file.data.name.replace(/[^A-Za-z0-9._-]/g,'_').slice(-160)||'attachment';const path=`${c.booking.patient_id}/${c.booking.id}/${randomUUID()}-${safe}`;const uploaded=await c.s.storage.from('clinical-attachments').upload(path,file.data,{contentType:file.data.type,upsert:false});if(uploaded.error)return{error:'upload'};const metadata=await c.s.from('clinical_attachments').insert({booking_id:c.booking.id,case_id:c.booking.case_id,encounter_id:encounterId,appointment_id:appointmentId,patient_id:c.booking.patient_id,doctor_id:c.doctorId,title,patient_visible:String(f.get('patient_visible'))==='yes',object_path:path,original_filename:file.data.name.slice(0,240),mime_type:file.data.type,file_size_bytes:file.data.size,uploaded_by:c.auth.userId});if(metadata.error){await c.s.storage.from('clinical-attachments').remove([path]);return{error:'save'}}refresh(locale,c.booking.id);return{success:'saved'}}
export async function downloadClinicalAttachmentAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,['PATIENT','DOCTOR','ADMIN','SUPER_ADMIN']);const path=String(f.get('path')??'');if(!path)return;const s=await getSupabaseBrowserClient();if(!s)return;const{data}=await s.storage.from('clinical-attachments').createSignedUrl(path,60);if(data?.signedUrl)redirect(data.signedUrl)}
