'use client';

import { useActionState, useState } from 'react';
import { BedDouble, Building2, CalendarDays, Camera, MapPin, UsersRound } from 'lucide-react';
import { Badge } from '@/src/components/ui/badge';
import { Button } from '@/src/components/ui/button';
import { Card, CardContent, CardHeader } from '@/src/components/ui/card';
import { Dialog } from '@/src/components/ui/dialog';
import { Input } from '@/src/components/ui/input';
import { Select } from '@/src/components/ui/select';
import { Textarea } from '@/src/components/ui/textarea';
import type { Locale } from '@/src/i18n/config';
import { localized } from '@/src/features/cases/data';
import { reserveAccommodationAction, saveAccommodationPreferenceAction, saveAccommodationPropertyAction, saveAccommodationRoomAction, setAccommodationPropertyStatusAction, updateAccommodationStatusAction, uploadAccommodationPhotoAction, type TravelActionState } from './actions';
import type { AccommodationBooking, AccommodationOption, AccommodationProperty, JourneyChoice } from './data';
import type { TravelDictionary } from './messages';

const initial:TravelActionState={};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}{children}</label>}
function Feedback({state,copy}:{state:TravelActionState;copy:TravelDictionary}){return state.error?<p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800" role="alert">{state.error==='invalid'?copy.invalid:state.error==='availability'?copy.availabilityError:copy.failed}</p>:state.success?<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{copy.saved}</p>:null}
function journeyLabel(j:JourneyChoice){const p=j.profile;return `${j.booking_reference} · ${p?.display_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||j.medical_case?.title||''}`}
const statusLabel=(copy:TravelDictionary,status:AccommodationBooking['status'])=>({HELD:copy.held,CONFIRMED:copy.confirmed,CHECKED_IN:copy.checkedIn,COMPLETED:copy.completed,CANCELLED:copy.cancelled})[status];
const money=(locale:Locale,value:number,currency:string)=>new Intl.NumberFormat(locale,{style:'currency',currency}).format(value);

function ReservationForm({copy,locale,journeys,options,admin,plain=false}:{copy:TravelDictionary;locale:Locale;journeys:JourneyChoice[];options:AccommodationOption[];admin:boolean;plain?:boolean}){
 const[state,action,pending]=useActionState(reserveAccommodationAction,initial);const[optionId,setOptionId]=useState(options[0]?.id??'');const[inDate,setInDate]=useState('');const[outDate,setOutDate]=useState('');const[rooms,setRooms]=useState(1);const option=options.find(x=>x.id===optionId);const nights=inDate&&outDate?Math.max(0,Math.round((new Date(`${outDate}T00:00:00Z`).getTime()-new Date(`${inDate}T00:00:00Z`).getTime())/86400000)):0;const total=option?nights*rooms*option.price_per_night:0;
 return <form action={action} className={plain?'grid gap-4':'grid gap-4 rounded-2xl bg-slate-50 p-4'}><input name="locale" type="hidden" value={locale}/><input name="arrangement" type="hidden" value={admin?'CAREBRIDGE_ARRANGED':'PATIENT_SELECTED'}/><h3 className="font-semibold">{admin?copy.newBooking:copy.requestStay}</h3><Feedback copy={copy} state={state}/><Field label={copy.patientJourney}><Select name="booking_id" required><option value="">{copy.choose}</option>{journeys.map(j=><option key={j.id} value={j.id}>{journeyLabel(j)}</option>)}</Select></Field><Field label={copy.roomOption}><Select name="room_option_id" onChange={e=>setOptionId(e.target.value)} required value={optionId}>{options.map(o=><option key={o.id} value={o.id}>{o.property?.property_name} · {o.room_type} · {money(locale,o.price_per_night,o.currency)}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label={copy.checkIn}><Input name="check_in_date" onChange={e=>setInDate(e.target.value)} required type="date"/></Field><Field label={copy.checkOut}><Input name="check_out_date" onChange={e=>setOutDate(e.target.value)} required type="date"/></Field><Field label={copy.rooms}><Input min="1" name="number_of_rooms" onChange={e=>setRooms(Math.max(1,Number(e.target.value)||1))} required type="number" value={rooms}/></Field><Field label={copy.guests}><Input defaultValue="1" min="1" name="guests" required type="number"/></Field></div><div className="grid gap-4 rounded-xl border border-blue-100 bg-blue-50/50 p-4 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{copy.nights}</p><p className="mt-1 text-xl font-bold">{nights}</p></div><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{copy.estimatedTotal}</p><p className="mt-1 text-xl font-bold">{option?money(locale,total,option.currency):'—'}</p></div></div>{admin?<Field label={copy.finalPrice}><Input min="0" name="final_price" step="0.01" type="number"/></Field>:null}<Field label={copy.notes}><Textarea maxLength={3000} name="notes"/></Field><Button disabled={!options.length} loading={pending}>{copy.save}</Button></form>
}

type AdminAccommodationForm = 'property'|'room'|'photo'|'booking';

function PropertyForm({copy,locale,cities}:{copy:TravelDictionary;locale:Locale;cities:Array<{id:string;name_i18n:Record<string,string>;country:{name_i18n:Record<string,string>}|null}>}){
 const[state,action,pending]=useActionState(saveAccommodationPropertyAction,initial);
 return <form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><Feedback copy={copy} state={state}/><Field label={copy.propertyName}><Input maxLength={240} name="property_name" required/></Field><Field label={copy.city}><Select name="city_id" required><option value="">{copy.choose}</option>{cities.map(c=><option key={c.id} value={c.id}>{localized(c.name_i18n,locale)} · {localized(c.country?.name_i18n,locale)}</option>)}</Select></Field><Field label={copy.address}><Input maxLength={500} name="location_address" required/></Field><Field label={copy.notes}><Textarea name="notes"/></Field><Field label={copy.status}><Select defaultValue="true" name="is_active"><option value="true">{copy.active}</option><option value="false">{copy.inactive}</option></Select></Field><Button loading={pending}>{copy.save}</Button></form>
}

function RoomForm({copy,locale,properties}:{copy:TravelDictionary;locale:Locale;properties:AccommodationProperty[]}){
 const[state,action,pending]=useActionState(saveAccommodationRoomAction,initial);
 return <form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><Feedback copy={copy} state={state}/><Field label={copy.property}><Select name="property_id" required><option value="">{copy.choose}</option>{properties.map(p=><option key={p.id} value={p.id}>{p.property_name}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={copy.roomType}><Input name="room_type" required/></Field><Field label={copy.availableRooms}><Input min="1" name="available_rooms" required type="number"/></Field><Field label={copy.pricePerNight}><Input min="0" name="price_per_night" required step="0.01" type="number"/></Field><Field label={copy.currency}><Input maxLength={3} name="currency" pattern="[A-Za-z]{3}" placeholder="USD / EUR / EGP" required/></Field></div><Field label={copy.mealPlan}><Input name="meal_plan" required/></Field><Field label={copy.wellness}><Textarea name="wellness_services" placeholder="Physiotherapy, recovery meals"/></Field><Field label={copy.notes}><Textarea name="notes"/></Field><input name="is_active" type="hidden" value="true"/><Button loading={pending}>{copy.save}</Button></form>
}

function PhotoForm({copy,locale,properties}:{copy:TravelDictionary;locale:Locale;properties:AccommodationProperty[]}){
 const[state,action,pending]=useActionState(uploadAccommodationPhotoAction,initial);
 return <form action={action} className="grid gap-4"><Feedback copy={copy} state={state}/><input name="locale" type="hidden" value={locale}/><Field label={copy.property}><Select name="property_id" required><option value="">{copy.choose}</option>{properties.map(p=><option key={p.id} value={p.id}>{p.property_name}</option>)}</Select></Field><Field label={copy.photo}><Input accept="image/jpeg,image/png,image/webp" name="photo" required type="file"/></Field><Button loading={pending}><Camera className="size-4"/>{copy.uploadPhoto}</Button></form>
}

export function AccommodationManager({copy,locale,cities,options,properties,reservations,journeys}:{copy:TravelDictionary;locale:Locale;cities:Array<{id:string;name_i18n:Record<string,string>;country:{name_i18n:Record<string,string>}|null}>;options:AccommodationOption[];properties:AccommodationProperty[];reservations:AccommodationBooking[];journeys:JourneyChoice[]}){
 const[activeForm,setActiveForm]=useState<AdminAccommodationForm|null>(null);
 const availableJourneys=journeys.filter(j=>!reservations.some(r=>r.booking_id===j.id&&['HELD','CONFIRMED','CHECKED_IN'].includes(r.status)));
 const activeOptions=options.filter(o=>o.is_active&&o.property?.is_active);
 const tabs:Array<{id:AdminAccommodationForm;label:string;icon:typeof Building2}>=[{id:'property',label:copy.addProperty,icon:Building2},{id:'room',label:copy.addRoom,icon:BedDouble},{id:'photo',label:copy.uploadPhoto,icon:Camera},{id:'booking',label:copy.newBooking,icon:CalendarDays}];
 const activeTab=tabs.find(tab=>tab.id===activeForm);
 return <div className="space-y-8"><Card className="border-blue-100 bg-[linear-gradient(135deg,#f8fbfd_0%,#eef6fa_100%)]"><CardContent className="flex flex-col gap-5 p-5 sm:p-6 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold text-slate-950">{copy.manageAccommodation}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">{copy.manageAccommodationDescription}</p></div><div className="grid gap-2 sm:grid-cols-2 lg:flex lg:flex-wrap">{tabs.map(({id,label,icon:Icon},index)=><Button key={id} onClick={()=>setActiveForm(id)} type="button" variant={index===0?'primary':'outline'}><Icon className="size-4"/>{label}</Button>)}</div></CardContent></Card><PropertyStatusList copy={copy} locale={locale} properties={properties}/><Card><CardHeader><h2 className="text-lg font-semibold">{copy.currentOptions}</h2></CardHeader><CardContent><OptionGrid copy={copy} locale={locale} options={options}/></CardContent></Card><Card><CardHeader><h2 className="text-lg font-semibold">{copy.patientBookings}</h2></CardHeader><CardContent>{reservations.length?<ReservationList admin copy={copy} locale={locale} reservations={reservations}/>:<p className="py-8 text-center text-sm text-slate-500">{copy.noBookings}</p>}</CardContent></Card><Dialog className="max-w-3xl" closeLabel={copy.close} description={copy.manageAccommodationDescription} onClose={()=>setActiveForm(null)} open={activeForm!==null} title={activeTab?.label??copy.manageAccommodation}><div className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-100 pb-3" role="tablist">{tabs.map(({id,label,icon:Icon})=><button aria-selected={activeForm===id} className={`inline-flex min-h-10 shrink-0 items-center gap-2 rounded-xl px-3.5 text-sm font-semibold transition ${activeForm===id?'bg-blue-50 text-blue-800':'text-slate-500 hover:bg-slate-50 hover:text-slate-800'}`} key={id} onClick={()=>setActiveForm(id)} role="tab" type="button"><Icon className="size-4"/>{label}</button>)}</div>{activeForm==='property'?<PropertyForm cities={cities} copy={copy} locale={locale}/>:activeForm==='room'?<RoomForm copy={copy} locale={locale} properties={properties}/>:activeForm==='photo'?<PhotoForm copy={copy} locale={locale} properties={properties}/>:activeForm==='booking'?<ReservationForm admin copy={copy} journeys={availableJourneys} locale={locale} options={activeOptions} plain/>:null}</Dialog></div>
}

function PropertyStatusList({copy,locale,properties}:{copy:TravelDictionary;locale:Locale;properties:AccommodationProperty[]}){return <Card><CardHeader><h2 className="text-lg font-semibold">{copy.property}</h2></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2">{properties.map(p=><div className="flex items-center justify-between gap-3 rounded-xl border p-3" key={p.id}><div><p className="font-semibold">{p.property_name}</p><p className="text-xs text-slate-500">{p.location_address}</p></div><form action={setAccommodationPropertyStatusAction}><input name="locale" type="hidden" value={locale}/><input name="property_id" type="hidden" value={p.id}/><input name="is_active" type="hidden" value={String(!p.is_active)}/><Button size="sm" type="submit" variant="outline">{p.is_active?copy.inactive:copy.active}</Button></form></div>)}</div></CardContent></Card>}

export function AccommodationPatient({copy,locale,options,reservations,journeys,preferences}:{copy:TravelDictionary;locale:Locale;options:AccommodationOption[];reservations:AccommodationBooking[];journeys:JourneyChoice[];preferences:Array<{booking_id:string;arrangement:string;notes:string|null}>}){
 const[prefState,prefAction,prefPending]=useActionState(saveAccommodationPreferenceAction,initial);const currentIds=new Set(reservations.filter(r=>['HELD','CONFIRMED','CHECKED_IN'].includes(r.status)).map(r=>r.booking_id));const availableJourneys=journeys.filter(j=>!currentIds.has(j.id));
 return <div className="space-y-6">{reservations.length?<Card><CardHeader><h2 className="text-lg font-semibold">{copy.patientBookings}</h2></CardHeader><CardContent><ReservationList copy={copy} locale={locale} reservations={reservations}/></CardContent></Card>:null}{availableJourneys.length?<><Card variant="form"><CardHeader><h2 className="text-lg font-semibold">{copy.choosePreference}</h2></CardHeader><CardContent><form action={prefAction} className="grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><input name="locale" type="hidden" value={locale}/><Field label={copy.patientJourney}><Select name="booking_id" required>{availableJourneys.map(j=><option key={j.id} value={j.id}>{journeyLabel(j)}</option>)}</Select></Field><Field label={copy.arrangement}><Select name="arrangement"><option value="PATIENT_WILL_CHOOSE">{copy.patientWillChoose}</option><option value="NOT_REQUIRED">{copy.notRequired}</option></Select></Field><Button className="self-end" loading={prefPending}>{copy.save}</Button><Feedback copy={copy} state={prefState}/></form>{preferences.map(p=><p className="mt-3 text-sm text-slate-600" key={p.booking_id}>{p.arrangement==='NOT_REQUIRED'?copy.notRequired:copy.patientWillChoose}</p>)}</CardContent></Card><Card><CardHeader><h2 className="text-lg font-semibold">{copy.currentOptions}</h2><p className="text-sm text-slate-600">{copy.browseDescription}</p></CardHeader><CardContent><OptionGrid copy={copy} locale={locale} options={options}/><div className="mt-6"><ReservationForm admin={false} copy={copy} journeys={availableJourneys} locale={locale} options={options}/></div></CardContent></Card></>:<p className="rounded-2xl border border-blue-100 bg-blue-50 p-5 text-sm text-blue-900">{copy.accommodationAlreadyArranged}</p>}</div>
}

function OptionGrid({copy,locale,options}:{copy:TravelDictionary;locale:Locale;options:AccommodationOption[]}){if(!options.length)return <p className="py-8 text-center text-sm text-slate-500">{copy.noOptions}</p>;return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{options.map(o=>{const photo=o.property?.photos?.[0];const url=photo&&process.env.NEXT_PUBLIC_SUPABASE_URL?`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/accommodation-media/${photo.object_path}`:null;return <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white" key={o.id}>{url?<div className="h-36 bg-cover bg-center" role="img" aria-label={o.property?.property_name} style={{backgroundImage:`url(${url})`}}/>:<div className="grid h-28 place-items-center bg-blue-50 text-blue-700"><Building2 className="size-8"/></div>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{o.property?.property_name}</h3><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin className="size-3"/>{o.property?.location_address}</p></div><Badge variant={o.is_active?'green':'slate'}>{o.is_active?copy.active:copy.inactive}</Badge></div><p className="mt-4 flex items-center gap-2 text-sm"><BedDouble className="size-4 text-blue-700"/>{o.room_type} · {o.meal_plan}</p><p className="mt-2 text-xl font-bold">{money(locale,o.price_per_night,o.currency)} <span className="text-xs font-normal text-slate-500">/ {copy.nights}</span></p><p className="mt-2 text-xs text-slate-500">{o.available_rooms} {copy.availableRooms}</p>{o.wellness_services.length?<p className="mt-3 text-xs text-slate-600">{o.wellness_services.join(' · ')}</p>:null}</div></article>})}</div>}
function ReservationList({copy,locale,reservations,admin=false}:{copy:TravelDictionary;locale:Locale;reservations:AccommodationBooking[];admin?:boolean}){return <div className="space-y-3">{reservations.map(r=><article className="rounded-2xl border border-slate-200 p-4" key={r.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{r.room_option?.property?.property_name} · {r.room_option?.room_type}</h3><p className="mt-1 text-sm text-slate-600">{r.booking?.booking_reference}</p></div><Badge variant={r.status==='CANCELLED'?'slate':'blue'}>{statusLabel(copy,r.status)}</Badge></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-4"><p className="flex items-center gap-2"><CalendarDays className="size-4"/>{r.check_in_date} → {r.check_out_date}</p><p>{r.nights} {copy.nights}</p><p className="flex items-center gap-2"><UsersRound className="size-4"/>{r.number_of_rooms} / {r.guests}</p><p className="font-semibold">{money(locale,r.final_price??r.total_amount,r.currency)}</p></div>{['HELD','CONFIRMED','CHECKED_IN'].includes(r.status)?<form action={updateAccommodationStatusAction} className="mt-4 flex flex-wrap gap-2"><input name="locale" type="hidden" value={locale}/><input name="accommodation_booking_id" type="hidden" value={r.id}/>{admin?(['CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED'] as const).map(s=><Button key={s} name="status" size="sm" type="submit" value={s} variant="outline">{statusLabel(copy,s)}</Button>):<Button name="status" size="sm" type="submit" value="CANCELLED" variant="outline">{copy.cancel}</Button>}</form>:null}</article>)}</div>}
