'use server';

import { randomUUID } from 'node:crypto';
import { revalidatePath } from 'next/cache';
import { isLocale, type Locale } from '@/src/i18n/config';
import { requireRoles } from '@/src/lib/auth/context';
import { getSupabaseServerClient } from '@/src/lib/supabase/server';
import { accommodationBookingSchema, accommodationDeleteSchema, accommodationPreferenceSchema, accommodationStatusSchema, passportSchema, propertySchema, roomSchema, travelPlanSchema } from './validation';

export interface TravelActionState { error?: 'invalid'|'unavailable'|'save'|'availability'|'conflict'; success?: 'saved' }
const adminRoles = ['ADMIN','SUPER_ADMIN'] as const;
const localeOf=(f:FormData):Locale=>{const l=String(f.get('locale')??'en');return isLocale(l)?l:'en'};
const nil=(v:string|undefined)=>v||null;
function refresh(locale:Locale){for(const portal of ['admin','patient']){revalidatePath(`/${locale}/${portal}/accommodation`);revalidatePath(`/${locale}/${portal}/travel`);}for(const portal of ['patient','provider'])revalidatePath(`/${locale}/${portal}/bookings`);}

export async function saveAccommodationPropertyAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,adminRoles);const p=propertySchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const v=p.data;const payload={property_name:v.property_name,city_id:v.city_id,location_address:v.location_address,notes:nil(v.notes),is_active:v.is_active==='true'};const result=v.property_id?await s.from('accommodation_properties').update(payload).eq('id',v.property_id):await s.from('accommodation_properties').insert({...payload,created_by:auth.userId});if(result.error)return{error:'save'};refresh(locale);return{success:'saved'};}
export async function saveAccommodationRoomAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,adminRoles);const p=roomSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const v=p.data;if(v.room_option_id){const[{data:existing},{data:bookings}]=await Promise.all([s.from('accommodation_room_options').select('property_id').eq('id',v.room_option_id).maybeSingle(),s.from('accommodation_bookings').select('number_of_rooms,status').eq('room_option_id',v.room_option_id)]);if(!existing||((bookings?.length??0)>0&&existing.property_id!==v.property_id))return{error:'invalid'};const reserved=(bookings??[]).filter(row=>['HELD','CONFIRMED','CHECKED_IN'].includes(row.status)).reduce((sum,row)=>sum+row.number_of_rooms,0);if(v.available_rooms<reserved)return{error:'availability'};}const payload={property_id:v.property_id,room_type:v.room_type,available_rooms:v.available_rooms,price_per_night:v.price_per_night,currency:v.currency,meal_plan:v.meal_plan,wellness_services:v.wellness_services.split(/[,\n]/).map(x=>x.trim()).filter(Boolean).slice(0,30),notes:nil(v.notes),is_active:v.is_active==='true'};const result=v.room_option_id?await s.from('accommodation_room_options').update(payload).eq('id',v.room_option_id):await s.from('accommodation_room_options').insert({...payload,created_by:auth.userId});if(result.error)return{error:'save'};refresh(locale);return{success:'saved'};}
export async function deleteAccommodationPropertyAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);await requireRoles(locale,adminRoles);const p=accommodationDeleteSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const{data:photos}=await s.from('accommodation_photos').select('object_path').eq('property_id',p.data.target_id);const result=await s.from('accommodation_properties').delete().eq('id',p.data.target_id);if(result.error)return{error:result.error.code==='23503'?'conflict':'save'};const paths=(photos??[]).map(photo=>photo.object_path);if(paths.length)await s.storage.from('accommodation-media').remove(paths);refresh(locale);return{success:'saved'};}
export async function deleteAccommodationRoomAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);await requireRoles(locale,adminRoles);const p=accommodationDeleteSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const result=await s.from('accommodation_room_options').delete().eq('id',p.data.target_id);if(result.error)return{error:result.error.code==='23503'?'conflict':'save'};refresh(locale);return{success:'saved'};}
export async function setAccommodationPropertyStatusAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,adminRoles);const id=String(f.get('property_id')??'');const active=String(f.get('is_active'))==='true';if(!id)return;const s=await getSupabaseServerClient();await s?.from('accommodation_properties').update({is_active:active}).eq('id',id);refresh(locale);}
export async function uploadAccommodationPhotoAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,adminRoles);const propertyId=String(f.get('property_id')??'');const file=f.get('photo');if(!propertyId||!(file instanceof File)||file.size<1||file.size>10485760||!['image/jpeg','image/png','image/webp'].includes(file.type))return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const ext=(file.name.split('.').pop()??'bin').replace(/[^a-z0-9]/gi,'').slice(0,8);const id=randomUUID();const path=`${propertyId}/${id}/${randomUUID()}.${ext}`;const up=await s.storage.from('accommodation-media').upload(path,file,{contentType:file.type,upsert:false});if(up.error)return{error:'save'};const saved=await s.from('accommodation_photos').insert({id,property_id:propertyId,object_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size,uploaded_by:auth.userId});if(saved.error){await s.storage.from('accommodation-media').remove([path]);return{error:'save'};}refresh(locale);return{success:'saved'};}
export async function saveAccommodationPreferenceAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PATIENT']);const p=accommodationPreferenceSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const{error}=await s.from('journey_accommodation_preferences').upsert({booking_id:p.data.booking_id,patient_id:auth.userId,arrangement:p.data.arrangement,notes:nil(p.data.notes),updated_by:auth.userId},{onConflict:'booking_id'});if(error)return{error:'save'};refresh(locale);return{success:'saved'};}
export async function reserveAccommodationAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PATIENT','ADMIN','SUPER_ADMIN']);const p=accommodationBookingSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const admin=auth.roles.some(r=>r==='ADMIN'||r==='SUPER_ADMIN');if(!admin&&p.data.arrangement!=='PATIENT_SELECTED')return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const v=p.data;const{error}=await s.rpc('reserve_accommodation',{target_booking_id:v.booking_id,target_room_option_id:v.room_option_id,target_arrangement:v.arrangement,target_check_in:v.check_in_date,target_check_out:v.check_out_date,target_rooms:v.number_of_rooms,target_guests:v.guests,target_final_price:v.final_price===''||v.final_price===undefined?null:v.final_price,target_notes:nil(v.notes)});if(error)return{error:error.message.includes('availability')||error.message.includes('already arranged')?'availability':'save'};refresh(locale);return{success:'saved'};}
export async function updateAccommodationStatusAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,['PATIENT','ADMIN','SUPER_ADMIN']);const p=accommodationStatusSchema.safeParse(Object.fromEntries(f));if(!p.success)return;const s=await getSupabaseServerClient();if(!s)return;await s.from('accommodation_bookings').update({status:p.data.status}).eq('id',p.data.accommodation_booking_id);refresh(locale);}
export async function saveTravelPlanAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PATIENT','ADMIN','SUPER_ADMIN']);const p=travelPlanSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const admin=auth.roles.some(r=>r==='ADMIN'||r==='SUPER_ADMIN');if(!admin&&p.data.travel_arrangement!=='PATIENT_SELF_ARRANGED')return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const{data:b}=await s.from('bookings').select('patient_id,journey_type').eq('id',p.data.booking_id).maybeSingle();if(!b||b.journey_type!=='INTERNATIONAL_MEDICAL_TRAVEL')return{error:'invalid'};const v=p.data;const timestamp=(x:string|undefined)=>x?new Date(x).toISOString():null;const payload={booking_id:v.booking_id,patient_id:b.patient_id,travel_arrangement:v.travel_arrangement,trip_type:v.trip_type,origin_location:nil(v.origin_location),destination_location:nil(v.destination_location),outbound_departure_at:timestamp(v.outbound_departure_at),outbound_arrival_at:timestamp(v.outbound_arrival_at),return_departure_at:timestamp(v.return_departure_at),return_arrival_at:timestamp(v.return_arrival_at),origin_airport:nil(v.origin_airport),destination_airport:nil(v.destination_airport),airline:nil(v.airline),outbound_flight_number:nil(v.outbound_flight_number),return_airline:nil(v.return_airline),return_flight_number:nil(v.return_flight_number),ticket_reference:nil(v.ticket_reference),cabin_class:nil(v.cabin_class),ticket_price:v.ticket_price===''||v.ticket_price===undefined?null:v.ticket_price,ticket_currency:nil(v.ticket_currency),booking_status:v.booking_status,travel_notes:nil(v.travel_notes),accommodation_mode:'NOT_REQUIRED',updated_by:auth.userId};const{error}=await s.from('travel_plans').upsert(payload,{onConflict:'booking_id'});if(error)return{error:'save'};refresh(locale);return{success:'saved'};}
export async function savePassportAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PATIENT','ADMIN','SUPER_ADMIN']);const p=passportSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const{data:b}=await s.from('bookings').select('patient_id').eq('id',p.data.booking_id).maybeSingle();if(!b)return{error:'invalid'};const{error}=await s.from('patient_passports').upsert({...p.data,patient_id:b.patient_id,updated_by:auth.userId},{onConflict:'patient_id'});if(error)return{error:'save'};refresh(locale);return{success:'saved'};}
export async function uploadTravelDocumentAction(_:TravelActionState,f:FormData):Promise<TravelActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,['PATIENT','ADMIN','SUPER_ADMIN']);const bookingId=String(f.get('booking_id')??'');const documentType=String(f.get('document_type')??'');const file=f.get('document');if(!bookingId||!['PASSPORT_COPY','TICKET','ITINERARY','OTHER'].includes(documentType)||!(file instanceof File)||file.size<1||file.size>15728640||!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))return{error:'invalid'};const s=await getSupabaseServerClient();if(!s)return{error:'unavailable'};const{data:b}=await s.from('bookings').select('patient_id').eq('id',bookingId).maybeSingle();if(!b)return{error:'invalid'};const ext=(file.name.split('.').pop()??'bin').replace(/[^a-z0-9]/gi,'').slice(0,8);const path=`${b.patient_id}/${bookingId}/${documentType}/${randomUUID()}.${ext}`;const up=await s.storage.from('travel-documents').upload(path,file,{contentType:file.type,upsert:false});if(up.error)return{error:'save'};const saved=await s.from('travel_documents').insert({booking_id:bookingId,patient_id:b.patient_id,document_type:documentType,object_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size,uploaded_by:auth.userId});if(saved.error){await s.storage.from('travel-documents').remove([path]);return{error:'save'};}refresh(locale);return{success:'saved'};}
