import { z } from 'zod';

const optional = (max: number) => z.string().trim().max(max).optional().default('');
export const propertySchema = z.object({ property_id: z.uuid().optional().or(z.literal('')), property_name: z.string().trim().min(2).max(240), city_id: z.uuid(), location_address: z.string().trim().min(2).max(500), notes: optional(3000), is_active: z.enum(['true','false']) });
export const roomSchema = z.object({ room_option_id: z.uuid().optional().or(z.literal('')), property_id: z.uuid(), room_type: z.string().trim().min(2).max(160), available_rooms: z.coerce.number().int().min(1).max(100000), price_per_night: z.coerce.number().min(0).max(999999999), currency: z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/), meal_plan: z.string().trim().min(2).max(160), wellness_services: optional(1000), notes: optional(3000), is_active: z.enum(['true','false']) });
export const accommodationPreferenceSchema = z.object({ booking_id: z.uuid(), arrangement: z.enum(['NOT_REQUIRED','PATIENT_WILL_CHOOSE']), notes: optional(2000) });
export const accommodationBookingSchema = z.object({ booking_id: z.uuid(), room_option_id: z.uuid(), arrangement: z.enum(['PATIENT_SELECTED','CAREBRIDGE_ARRANGED']), check_in_date: z.iso.date(), check_out_date: z.iso.date(), number_of_rooms: z.coerce.number().int().min(1).max(100), guests: z.coerce.number().int().min(1).max(500), final_price: z.union([z.literal(''), z.coerce.number().min(0).max(999999999)]).optional(), notes: optional(3000) }).refine(v => v.check_out_date > v.check_in_date, { path: ['check_out_date'], message: 'invalid stay' });
export const accommodationStatusSchema = z.object({ accommodation_booking_id: z.uuid(), status: z.enum(['HELD','CONFIRMED','CHECKED_IN','COMPLETED','CANCELLED']) });
export const travelPlanSchema = z.object({ booking_id: z.uuid(), travel_arrangement: z.enum(['PATIENT_SELF_ARRANGED','CAREBRIDGE_ARRANGED']), trip_type: z.enum(['ONE_WAY','RETURN_ONLY','ROUND_TRIP']), origin_location: optional(240), destination_location: optional(240), outbound_departure_at: z.string().optional(), outbound_arrival_at: z.string().optional(), return_departure_at: z.string().optional(), return_arrival_at: z.string().optional(), origin_airport: optional(180), destination_airport: optional(180), airline: optional(180), outbound_flight_number: optional(40), return_airline: optional(180), return_flight_number: optional(40), ticket_reference: optional(180), cabin_class: optional(80), ticket_price: z.union([z.literal(''), z.coerce.number().min(0).max(999999999)]).optional(), ticket_currency: z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/).optional().or(z.literal('')), booking_status: z.enum(['DRAFT','HELD','CONFIRMED','TICKETED','COMPLETED','CANCELLED']), travel_notes: optional(3000) }).refine(v => v.trip_type !== 'ROUND_TRIP' || Boolean(v.return_departure_at), { path: ['return_departure_at'], message: 'required' }).refine(v => v.ticket_price === '' || v.ticket_price === undefined || Boolean(v.ticket_currency), { path: ['ticket_currency'], message: 'required' });
export const passportSchema = z.object({ booking_id: z.uuid(), full_name_as_passport: z.string().trim().min(2).max(240), passport_number: z.string().trim().min(3).max(40), nationality: z.string().trim().min(2).max(120), date_of_birth: z.iso.date(), issue_date: z.iso.date(), expiry_date: z.iso.date() }).refine(v => v.expiry_date > v.issue_date, { path: ['expiry_date'], message: 'invalid' });
