import type { PortalKey } from '@/src/config/roles';
import type { Locale } from '@/src/i18n/config';
import type { Dictionary } from '@/src/i18n/messages/en';
import type { NotificationRecord } from '@/src/types/domain';
import { getJourneyDictionary } from '@/src/features/journey/messages';
import { getOperationsDictionary } from '@/src/features/operations/messages';

export function notificationText(record: NotificationRecord, locale: Locale, copy: Dictionary['notifications']) {
  const journey = getJourneyDictionary(locale).notifications;
  const key = record.title_key?.replace('part4.notifications.', '') as keyof typeof journey | undefined;
  const messageKey = record.message_key?.replace('part4.notifications.', '') as keyof typeof journey | undefined;
  if(record.title_key?.startsWith('part5.notifications.')){const operations=getOperationsDictionary(locale);const event=record.title_key.replace('part5.notifications.','').replace(/Title$/,'');const phrases:Record<Locale,Record<string,string>>={en:{appointmentconfirmed:'Appointment confirmed',appointmentrescheduled:'Appointment rescheduled',appointmentcancelled:'Appointment cancelled',invoiceissued:'Invoice issued',paymentrecorded:'Manual payment recorded',paymentcompleted:'Payment tracking completed',travelupdated:'Travel information updated',transportplanned:'Pickup or transport planned',transportconfirmed:'Transport confirmed'},fr:{appointmentconfirmed:'Rendez-vous confirmé',appointmentrescheduled:'Rendez-vous replanifié',appointmentcancelled:'Rendez-vous annulé',invoiceissued:'Facture émise',paymentrecorded:'Paiement manuel enregistré',paymentcompleted:'Suivi du paiement terminé',travelupdated:'Informations de voyage mises à jour',transportplanned:'Transport planifié',transportconfirmed:'Transport confirmé'},ar:{appointmentconfirmed:'تم تأكيد الموعد',appointmentrescheduled:'تمت إعادة جدولة الموعد',appointmentcancelled:'تم إلغاء الموعد',invoiceissued:'تم إصدار الفاتورة',paymentrecorded:'تم تسجيل الدفعة اليدوية',paymentcompleted:'اكتمل تتبع الدفع',travelupdated:'تم تحديث معلومات السفر',transportplanned:'تم تخطيط النقل',transportconfirmed:'تم تأكيد النقل'}};const message=phrases[locale][event]??operations.title;return{title:message,message}}
  if(record.title_key?.startsWith('part6.notifications.')){const event=record.title_key.replace('part6.notifications.','').replace(/Title$/,'');const phrases:Record<Locale,Record<string,string>>={en:{prescriptionissued:'Prescription issued',labordered:'Laboratory order created',labscheduled:'Laboratory visit scheduled',labresult_available:'Laboratory result available',labresult_released:'Laboratory result released',radiologyordered:'Radiology order created',radiologyresult_available:'Radiology result available',radiologyresult_released:'Radiology result released',follow_upplanned:'Follow-up recommended',follow_upscheduled:'Follow-up scheduled',follow_uppending:'Follow-up pending',journeycompleted:'Clinical journey completed'},fr:{prescriptionissued:'Ordonnance publiée',labordered:'Analyse de laboratoire prescrite',labscheduled:'Visite au laboratoire planifiée',labresult_available:'Résultat de laboratoire disponible',labresult_released:'Résultat de laboratoire publié',radiologyordered:'Examen radiologique prescrit',radiologyresult_available:'Résultat radiologique disponible',radiologyresult_released:'Résultat radiologique publié',follow_upplanned:'Suivi recommandé',follow_upscheduled:'Suivi planifié',follow_uppending:'Suivi en attente',journeycompleted:'Parcours clinique terminé'},ar:{prescriptionissued:'تم إصدار وصفة طبية',labordered:'تم إنشاء طلب مختبر',labscheduled:'تم تحديد موعد المختبر',labresult_available:'نتيجة المختبر متاحة',labresult_released:'تمت إتاحة نتيجة المختبر',radiologyordered:'تم إنشاء طلب أشعة',radiologyresult_available:'نتيجة الأشعة متاحة',radiologyresult_released:'تمت إتاحة نتيجة الأشعة',follow_upplanned:'تمت التوصية بمتابعة',follow_upscheduled:'تم تحديد المتابعة',follow_uppending:'المتابعة معلقة',journeycompleted:'اكتملت الرحلة السريرية'}};const message=phrases[locale][event]??copy.foundationTitle;return{title:message,message}}
  return { title: key && journey[key] ? journey[key] : copy.foundationTitle, message: messageKey && journey[messageKey] ? journey[messageKey] : copy.foundationMessage };
}
export function notificationHref(record: NotificationRecord, locale: Locale, portal: PortalKey) {
  if (!record.related_entity_id) return `/${locale}/notifications`;
  if (record.related_entity_type === 'offer' && ['patient','provider','doctor'].includes(portal)) return `/${locale}/${portal}/offers/${record.related_entity_id}`;
  if (record.related_entity_type === 'booking' && ['patient','provider','doctor'].includes(portal)) return `/${locale}/${portal}/bookings/${record.related_entity_id}`;
  if (record.related_entity_type === 'appointment' && ['patient','provider','doctor'].includes(portal)) return `/${locale}/${portal}/appointments/${record.related_entity_id}`;
  return `/${locale}/notifications`;
}
