import type { PortalKey } from '@/src/config/roles';
import type { Locale } from '@/src/i18n/config';
import type { Dictionary } from '@/src/i18n/messages/en';
import type { NotificationRecord } from '@/src/types/domain';
import { getJourneyDictionary } from '@/src/features/journey/messages';
import { getOperationsDictionary } from '@/src/features/operations/messages';

export function notificationText(record: NotificationRecord, locale: Locale, copy: Dictionary['notifications']) {
  if(record.title_key?.startsWith('reflection.notifications.')){
    const event=record.type;
    const phrases:Record<Locale,Record<string,{title:string;message:string}>>={
      en:{'journey.service_assigned':{title:'A Journey service was assigned to you',message:'Open the Treatment Journey to review the patient, service and schedule.'},'appointment.assigned':{title:'A new appointment was booked',message:'Open the appointment to review its time and Journey context.'},'appointment.rescheduled':{title:'An appointment was rescheduled',message:'Review the updated date and time in your schedule.'},'appointment.cancelled':{title:'An appointment was cancelled',message:'Open the appointment to review its current status.'},'settlement.pending':{title:'Service settlement is pending',message:'Your service account has been updated.'},'settlement.partially_settled':{title:'A service was partially settled',message:'Open your account to review the settled and outstanding amounts.'},'settlement.settled':{title:'A service was settled',message:'Open your account to review the completed settlement.'},'settlement.cancelled':{title:'A service settlement was cancelled',message:'Open your account to review the current status.'}},
      fr:{'journey.service_assigned':{title:'Un service de parcours vous a été attribué',message:'Ouvrez le parcours pour consulter le patient, le service et le planning.'},'appointment.assigned':{title:'Un nouveau rendez-vous a été planifié',message:'Ouvrez le rendez-vous pour consulter son horaire et son parcours.'},'appointment.rescheduled':{title:'Un rendez-vous a été replanifié',message:'Consultez la nouvelle date et heure dans votre planning.'},'appointment.cancelled':{title:'Un rendez-vous a été annulé',message:'Ouvrez le rendez-vous pour consulter son statut.'},'settlement.pending':{title:'Règlement du service en attente',message:'Votre compte prestataire a été mis à jour.'},'settlement.partially_settled':{title:'Service partiellement réglé',message:'Ouvrez votre compte pour consulter les montants réglés et restants.'},'settlement.settled':{title:'Service réglé',message:'Ouvrez votre compte pour consulter le règlement.'},'settlement.cancelled':{title:'Règlement annulé',message:'Ouvrez votre compte pour consulter le statut actuel.'}},
      ar:{'journey.service_assigned':{title:'تم إسناد خدمة ضمن رحلة علاج إليك',message:'افتح رحلة العلاج لمراجعة المريض والخدمة والموعد.'},'appointment.assigned':{title:'تم حجز موعد جديد',message:'افتح الموعد لمراجعة توقيته وارتباطه برحلة العلاج.'},'appointment.rescheduled':{title:'تمت إعادة جدولة موعد',message:'راجع التاريخ والوقت الجديدين في جدولك.'},'appointment.cancelled':{title:'تم إلغاء موعد',message:'افتح الموعد لمراجعة حالته الحالية.'},'settlement.pending':{title:'تسوية الخدمة قيد الانتظار',message:'تم تحديث حساب مستحقات خدماتك.'},'settlement.partially_settled':{title:'تمت تسوية جزء من قيمة الخدمة',message:'افتح حسابك لمراجعة المبلغ المسدد والمتبقي.'},'settlement.settled':{title:'اكتملت تسوية قيمة الخدمة',message:'افتح حسابك لمراجعة التسوية المكتملة.'},'settlement.cancelled':{title:'تم إلغاء تسوية الخدمة',message:'افتح حسابك لمراجعة الحالة الحالية.'}}
    };
    return phrases[locale][event]??{title:locale==='ar'?'تم تحديث رحلة العلاج':locale==='fr'?'Parcours de soins mis à jour':'Treatment Journey updated',message:locale==='ar'?'افتح رحلة العلاج لمراجعة أحدث التفاصيل.':locale==='fr'?'Ouvrez le parcours pour consulter les dernières informations.':'Open the Treatment Journey to review the latest details.'};
  }
  if(record.type.startsWith('reminder.')){const kind=record.type.replace('reminder.','');const phrases:Record<Locale,Record<string,{title:string;message:string}>>={en:{procedure:{title:'Procedure reminder',message:'Your procedure is in 48 hours. Open the appointment for timing and preparation details.'},doctor_appointment:{title:'Doctor appointment reminder',message:'Your doctor appointment is in 5 hours.'},lab_appointment:{title:'Laboratory appointment reminder',message:'Your laboratory appointment is in 5 hours.'},radiology_appointment:{title:'Radiology appointment reminder',message:'Your radiology appointment is in 5 hours.'},medication_dose:{title:'Medication reminder',message:'A prescribed medication dose is due in 15 minutes. Open your care journey for the doctor’s instructions.'}},fr:{procedure:{title:'Rappel d’intervention',message:'Votre intervention est prévue dans 48 heures. Ouvrez le rendez-vous pour consulter les horaires et consignes.'},doctor_appointment:{title:'Rappel de rendez-vous médical',message:'Votre rendez-vous médical est prévu dans 5 heures.'},lab_appointment:{title:'Rappel de laboratoire',message:'Votre rendez-vous au laboratoire est prévu dans 5 heures.'},radiology_appointment:{title:'Rappel de radiologie',message:'Votre rendez-vous de radiologie est prévu dans 5 heures.'},medication_dose:{title:'Rappel de médicament',message:'Une prise prescrite est prévue dans 15 minutes. Consultez votre parcours pour les instructions du médecin.'}},ar:{procedure:{title:'تذكير بالإجراء الطبي',message:'موعد الإجراء الطبي بعد 48 ساعة. افتح الموعد للاطلاع على التوقيت وتعليمات الاستعداد.'},doctor_appointment:{title:'تذكير بموعد الطبيب',message:'موعدك مع الطبيب بعد 5 ساعات.'},lab_appointment:{title:'تذكير بموعد التحاليل',message:'موعد التحاليل بعد 5 ساعات.'},radiology_appointment:{title:'تذكير بموعد الأشعة',message:'موعد الأشعة بعد 5 ساعات.'},medication_dose:{title:'تذكير بموعد الدواء',message:'حان موعد جرعة موصوفة خلال 15 دقيقة. افتح رحلة العلاج للاطلاع على تعليمات الطبيب.'}}};return phrases[locale][kind]??{title:copy.foundationTitle,message:copy.foundationMessage}}
  if(record.title_key==='part6.notifications.treatmentrecommendedTitle'||record.title_key==='part6.notifications.procedurescheduledTitle'){const procedure=record.title_key.includes('procedure');const phrases:Record<Locale,{treatment:{title:string;message:string};procedure:{title:string;message:string}}>={en:{treatment:{title:'Your treatment recommendation is ready',message:'Open your care journey to review the doctor’s recommendation.'},procedure:{title:'Your procedure was scheduled',message:'Open your care journey to review the date, hospital and clinical instructions.'}},fr:{treatment:{title:'Votre recommandation thérapeutique est disponible',message:'Ouvrez votre parcours pour consulter la recommandation du médecin.'},procedure:{title:'Votre intervention a été planifiée',message:'Ouvrez votre parcours pour consulter la date, l’hôpital et les instructions.'}},ar:{treatment:{title:'التوصية العلاجية جاهزة',message:'افتح رحلة العلاج للاطلاع على توصية الطبيب.'},procedure:{title:'تمت جدولة الإجراء الطبي',message:'افتح رحلة العلاج للاطلاع على الموعد والمستشفى والتعليمات الطبية.'}}};return procedure?phrases[locale].procedure:phrases[locale].treatment}
  if(record.title_key?.startsWith('journey.notifications.')){const patientSelected=record.title_key.includes('patientSelected');const phrases:Record<Locale,{patient:{title:string;message:string};admin:{title:string;message:string}}>={en:{patient:{title:'Your care journey was updated',message:'Open your care journey to review the latest coordination status.'},admin:{title:'A patient selected a care provider',message:'Open the care journey to review and confirm the patient’s choice.'}},fr:{patient:{title:'Votre parcours de soins a été mis à jour',message:'Ouvrez votre parcours pour consulter le dernier statut de coordination.'},admin:{title:'Un patient a choisi un prestataire de soins',message:'Ouvrez le parcours pour vérifier et confirmer son choix.'}},ar:{patient:{title:'تم تحديث رحلة علاجك',message:'افتح رحلة العلاج للاطلاع على أحدث حالة للتنسيق.'},admin:{title:'اختار مريض مقدم الرعاية',message:'افتح رحلة العلاج لمراجعة اختيار المريض وتأكيده.'}}};return patientSelected?phrases[locale].admin:phrases[locale].patient}
  if(record.title_key?.startsWith('travel.notifications.')){const event=record.title_key.replace('travel.notifications.','').replace(/Title$/,'');const phrases:Record<Locale,Record<string,string>>={en:{adminRequest:'A patient updated an accommodation request',accommodation:'Accommodation arrangements were updated',adminTravel:'A patient updated travel coordination details'},fr:{adminRequest:'Un patient a mis à jour une demande d’hébergement',accommodation:'Les dispositions d’hébergement ont été mises à jour',adminTravel:'Un patient a mis à jour ses informations de voyage'},ar:{adminRequest:'حدّث مريض طلب الإقامة',accommodation:'تم تحديث ترتيبات الإقامة',adminTravel:'حدّث مريض بيانات تنسيق السفر'}};const message=phrases[locale][event]??copy.foundationTitle;return{title:message,message}}
  if(record.title_key?.startsWith('core.notifications.')){const event=record.title_key.replace('core.notifications.','').replace(/Title$/,'');const phrases:Record<Locale,Record<string,string>>={en:{caseAssigned:'A medical case was assigned for your review',providerAssigned:'A medical case was shared with your care team',recommendation:'Your treatment recommendation is ready',offerReady:'A reviewed case is ready for an offer'},fr:{caseAssigned:'Un dossier médical vous a été attribué',providerAssigned:'Un dossier médical a été partagé avec votre équipe',recommendation:'Votre recommandation de traitement est disponible',offerReady:'Un dossier examiné est prêt pour une offre'},ar:{caseAssigned:'أُسندت إليك حالة طبية لمراجعتها',providerAssigned:'تمت مشاركة حالة طبية مع فريق الرعاية',recommendation:'التوصية العلاجية جاهزة',offerReady:'حالة طبية مراجَعة جاهزة لإعداد عرض'}};const message=phrases[locale][event]??copy.foundationTitle;return{title:message,message}}
  const journey = getJourneyDictionary(locale).notifications;
  const key = record.title_key?.replace('part4.notifications.', '') as keyof typeof journey | undefined;
  const messageKey = record.message_key?.replace('part4.notifications.', '') as keyof typeof journey | undefined;
  if(record.title_key?.startsWith('part5.notifications.')){const operations=getOperationsDictionary(locale);const event=record.title_key.replace('part5.notifications.','').replace(/Title$/,'');const phrases:Record<Locale,Record<string,string>>={en:{appointmentconfirmed:'Appointment confirmed',appointmentrescheduled:'Appointment rescheduled',appointmentcancelled:'Appointment cancelled',invoiceissued:'Invoice issued',paymentrecorded:'Manual payment recorded',paymentcompleted:'Payment tracking completed',travelupdated:'Travel information updated',transportplanned:'Pickup or transport planned',transportconfirmed:'Transport confirmed'},fr:{appointmentconfirmed:'Rendez-vous confirmé',appointmentrescheduled:'Rendez-vous replanifié',appointmentcancelled:'Rendez-vous annulé',invoiceissued:'Facture émise',paymentrecorded:'Paiement manuel enregistré',paymentcompleted:'Suivi du paiement terminé',travelupdated:'Informations de voyage mises à jour',transportplanned:'Transport planifié',transportconfirmed:'Transport confirmé'},ar:{appointmentconfirmed:'تم تأكيد الموعد',appointmentrescheduled:'تمت إعادة جدولة الموعد',appointmentcancelled:'تم إلغاء الموعد',invoiceissued:'تم إصدار الفاتورة',paymentrecorded:'تم تسجيل الدفعة اليدوية',paymentcompleted:'اكتمل تتبع الدفع',travelupdated:'تم تحديث معلومات السفر',transportplanned:'تم تخطيط النقل',transportconfirmed:'تم تأكيد النقل'}};const message=phrases[locale][event]??operations.title;return{title:message,message}}
  if(record.title_key?.startsWith('part6.notifications.')){const event=record.title_key.replace('part6.notifications.','').replace(/Title$/,'');const phrases:Record<Locale,Record<string,string>>={en:{prescriptionissued:'Prescription issued',labordered:'Laboratory order created',labscheduled:'Laboratory visit scheduled',labresult_available:'Laboratory result available',labresult_released:'Laboratory result released',radiologyordered:'Radiology order created',radiologyresult_available:'Radiology result available',radiologyresult_released:'Radiology result released',follow_upplanned:'Follow-up recommended',follow_upscheduled:'Follow-up scheduled',follow_uppending:'Follow-up pending',journeycompleted:'Clinical journey completed'},fr:{prescriptionissued:'Ordonnance publiée',labordered:'Analyse de laboratoire prescrite',labscheduled:'Visite au laboratoire planifiée',labresult_available:'Résultat de laboratoire disponible',labresult_released:'Résultat de laboratoire publié',radiologyordered:'Examen radiologique prescrit',radiologyresult_available:'Résultat radiologique disponible',radiologyresult_released:'Résultat radiologique publié',follow_upplanned:'Suivi recommandé',follow_upscheduled:'Suivi planifié',follow_uppending:'Suivi en attente',journeycompleted:'Parcours clinique terminé'},ar:{prescriptionissued:'تم إصدار وصفة طبية',labordered:'تم إنشاء طلب مختبر',labscheduled:'تم تحديد موعد المختبر',labresult_available:'نتيجة المختبر متاحة',labresult_released:'تمت إتاحة نتيجة المختبر',radiologyordered:'تم إنشاء طلب أشعة',radiologyresult_available:'نتيجة الأشعة متاحة',radiologyresult_released:'تمت إتاحة نتيجة الأشعة',follow_upplanned:'تمت التوصية بمتابعة',follow_upscheduled:'تم تحديد المتابعة',follow_uppending:'المتابعة معلقة',journeycompleted:'اكتملت الرحلة السريرية'}};const message=phrases[locale][event]??copy.foundationTitle;return{title:message,message}}
  return { title: key && journey[key] ? journey[key] : copy.foundationTitle, message: messageKey && journey[messageKey] ? journey[messageKey] : copy.foundationMessage };
}
export function notificationHref(record: NotificationRecord, locale: Locale, portal: PortalKey) {
  if (!record.related_entity_id) return `/${locale}/notifications`;
  if(record.type==='reminder.medication_dose'&&portal==='patient'&&typeof record.data.booking_id==='string')return `/${locale}/patient/journeys/${record.data.booking_id}#medical-history`;
  if(record.type.startsWith('reminder.')&&record.related_entity_type==='appointment'&&portal==='patient')return `/${locale}/patient/appointments/${record.related_entity_id}`;
  if (record.type.startsWith('accommodation.') && portal === 'patient' && record.related_entity_id) return `/${locale}/patient/journeys/${record.related_entity_id}#accommodation`;
  if (record.type.startsWith('accommodation.') && portal === 'admin') return `/${locale}/admin/accommodation`;
  if (record.type.startsWith('travel.') && portal === 'patient' && record.related_entity_id) return `/${locale}/patient/journeys/${record.related_entity_id}#travel`;
  if (record.type.startsWith('travel.') && portal === 'admin') return `/${locale}/admin/travel`;
  if (record.related_entity_type === 'booking' && portal === 'admin') return `/${locale}/admin/journeys/${record.related_entity_id}`;
  if (record.related_entity_type === 'offer' && ['patient','provider','doctor'].includes(portal)) return `/${locale}/${portal}/offers/${record.related_entity_id}`;
  if (record.related_entity_type === 'booking' && portal === 'patient') return `/${locale}/patient/journeys/${record.related_entity_id}`;
  if (record.related_entity_type === 'booking' && ['provider','doctor'].includes(portal)) return `/${locale}/${portal}/bookings/${record.related_entity_id}`;
  if (record.related_entity_type === 'appointment' && ['patient','provider','doctor'].includes(portal)) return `/${locale}/${portal}/appointments/${record.related_entity_id}`;
  if (record.related_entity_type === 'medical_case' && portal === 'patient') return `/${locale}/patient/cases/${record.related_entity_id}`;
  if (record.related_entity_type === 'medical_case' && portal === 'doctor') return `/${locale}/doctor/cases/${record.related_entity_id}`;
  if (record.related_entity_type === 'provider_case' && portal === 'provider') return `/${locale}/provider/cases/${record.related_entity_id}/offers/new`;
  if (record.related_entity_type === 'lab_order' && portal === 'provider') return `/${locale}/provider/diagnostics/lab/${record.related_entity_id}`;
  if (record.related_entity_type === 'radiology_order' && portal === 'provider') return `/${locale}/provider/diagnostics/radiology/${record.related_entity_id}`;
  if (record.related_entity_type === 'service_settlement' && ['doctor','provider'].includes(portal)) return `/${locale}/${portal}/account`;
  return `/${locale}/notifications`;
}
