
import {revalidatePath} from '@/src/react-app/compat/cache';
import {isLocale,type Locale} from '@/src/i18n/config';
import {requireRoles} from '@/src/lib/auth/context';
import {getSupabaseBrowserClient} from '@/src/lib/supabase/browser';
import {appointmentSchema,invoiceSchema,journeyTypeSchema,paymentSchema,transportSchema,travelSchema} from './validation';

const randomUUID=()=>crypto.randomUUID();
export interface OperationsActionState{error?:string;success?:string}
const managerRoles=['PROVIDER','HOSPITAL_ADMIN','HOSPITAL_COORDINATOR','PHARMACY','ADMIN','SUPER_ADMIN'] as const;
const scheduleRoles=[...managerRoles,'DOCTOR'] as const;
const localeOf=(f:FormData):Locale=>{const l=String(f.get('locale')??'en');return isLocale(l)?l:'en'};
const nil=(v:string|undefined)=>v||null;
async function bookingFor(id:string){const s=await getSupabaseBrowserClient();if(!s)return null;const{data}=await s.from('bookings').select('*').eq('id',id).maybeSingle();return data?{supabase:s,booking:data}:null;}
function refresh(locale:Locale,id:string){for(const p of ['patient','provider','doctor']){revalidatePath(`/${locale}/${p}/bookings/${id}`);revalidatePath(`/${locale}/${p}/appointments`);}}

export async function saveJourneyTypeAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);await requireRoles(locale,managerRoles);const p=journeyTypeSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const ctx=await bookingFor(p.data.booking_id);if(!ctx)return{error:'unavailable'};const{error}=await ctx.supabase.from('bookings').update({journey_type:p.data.journey_type,journey_timezone:p.data.journey_timezone}).eq('id',p.data.booking_id);if(error)return{error:'save'};refresh(locale,p.data.booking_id);return{success:'saved'};}
export async function saveAppointmentAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,scheduleRoles);const p=appointmentSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const ctx=await bookingFor(p.data.booking_id);if(!ctx)return{error:'unavailable'};const v=p.data,b=ctx.booking;const base={appointment_type:v.appointment_type,scheduled_at:new Date(v.scheduled_at).toISOString(),timezone:v.timezone,duration_minutes:v.duration_minutes,location_name:v.location_name,location_details:nil(v.location_details),instructions:nil(v.instructions),provider_notes:nil(v.provider_notes),doctor_id:b.doctor_id};let result;if(v.appointment_id)result=await ctx.supabase.from('appointments').update({...base,status:v.status}).eq('id',v.appointment_id).eq('booking_id',b.id);else result=await ctx.supabase.from('appointments').insert({...base,booking_id:b.id,patient_id:b.patient_id,provider_type:b.provider_type,hospital_id:b.hospital_id,pharmacy_id:b.pharmacy_id,radiology_center_id:b.radiology_center_id,medical_laboratory_id:b.medical_laboratory_id,status:'REQUESTED',created_by:auth.userId});if(result.error)return{error:'save'};refresh(locale,b.id);return{success:'saved'};}
export async function setAppointmentStatusAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,[...scheduleRoles,'PATIENT']);const id=String(f.get('appointment_id')??''),booking=String(f.get('booking_id')??''),status=String(f.get('status')??'');if(!id||!booking||!['CONFIRMED','RESCHEDULED','COMPLETED','CANCELLED','NO_SHOW'].includes(status))return;const s=await getSupabaseBrowserClient();await s?.from('appointments').update({status}).eq('id',id).eq('booking_id',booking);refresh(locale,booking);}
export async function createInvoiceAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,managerRoles);const p=invoiceSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const ctx=await bookingFor(p.data.booking_id);if(!ctx)return{error:'unavailable'};const b=ctx.booking,v=p.data;const{data:invoice,error}=await ctx.supabase.from('invoices').insert({invoice_number:`CBI-${randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`,booking_id:b.id,offer_id:b.offer_id,patient_id:b.patient_id,provider_type:b.provider_type,hospital_id:b.hospital_id,pharmacy_id:b.pharmacy_id,radiology_center_id:b.radiology_center_id,medical_laboratory_id:b.medical_laboratory_id,currency:v.currency,due_date:nil(v.due_date),notes:nil(v.notes),created_by:auth.userId}).select('id').single();if(error||!invoice)return{error:'save'};const item=await ctx.supabase.from('invoice_items').insert({invoice_id:invoice.id,description:v.description,quantity:v.quantity,unit_amount:v.unit_amount});if(item.error)return{error:'save'};refresh(locale,b.id);return{success:'saved'};}
export async function issueInvoiceAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,managerRoles);const id=String(f.get('invoice_id')??''),booking=String(f.get('booking_id')??'');const s=await getSupabaseBrowserClient();await s?.from('invoices').update({status:'ISSUED'}).eq('id',id).eq('booking_id',booking).eq('status','DRAFT');refresh(locale,booking);}
export async function recordPaymentAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,managerRoles);const p=paymentSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'unavailable'};const{data:i}=await s.from('invoices').select('booking_id,patient_id,currency').eq('id',p.data.invoice_id).maybeSingle();if(!i)return{error:'save'};const v=p.data;const{error}=await s.from('payment_records').insert({invoice_id:v.invoice_id,booking_id:i.booking_id,patient_id:i.patient_id,amount:v.amount,currency:i.currency,paid_at:new Date(v.paid_at).toISOString(),method:v.method,reference_number:nil(v.reference_number),notes:nil(v.notes),recorded_by:auth.userId});if(error)return{error:'save'};refresh(locale,i.booking_id);return{success:'saved'};}
export async function uploadPaymentProofAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,managerRoles);const paymentId=String(f.get('payment_id')??'');const file=f.get('proof');if(!(file instanceof File)||!paymentId)return{error:'invalid'};if(file.size<1||file.size>10485760||!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type))return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'unavailable'};const{data:p}=await s.from('payment_records').select('booking_id,patient_id').eq('id',paymentId).maybeSingle();if(!p)return{error:'save'};const ext=(file.name.split('.').pop()??'bin').replace(/[^a-z0-9]/gi,'').slice(0,8);const path=`${p.patient_id}/${p.booking_id}/${paymentId}/${randomUUID()}.${ext}`;const upload=await s.storage.from('payment-proofs').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)return{error:'save'};const saved=await s.from('payment_documents').insert({payment_id:paymentId,booking_id:p.booking_id,patient_id:p.patient_id,object_path:path,original_filename:file.name,mime_type:file.type,file_size_bytes:file.size,uploaded_by:auth.userId});if(saved.error){await s.storage.from('payment-proofs').remove([path]);return{error:'save'};}refresh(locale,p.booking_id);return{success:'saved'};}
export async function saveTravelAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,managerRoles);const p=travelSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const ctx=await bookingFor(p.data.booking_id);if(!ctx)return{error:'unavailable'};const v=p.data;const payload={...v,patient_id:ctx.booking.patient_id,arrival_at:v.arrival_at?new Date(v.arrival_at).toISOString():null,departure_at:v.departure_at?new Date(v.departure_at).toISOString():null,airline:nil(v.airline),arrival_flight_number:nil(v.arrival_flight_number),departure_flight_number:nil(v.departure_flight_number),origin_airport:nil(v.origin_airport),destination_airport:nil(v.destination_airport),arrival_terminal:nil(v.arrival_terminal),travel_notes:nil(v.travel_notes),accommodation_name:nil(v.accommodation_name),accommodation_address:nil(v.accommodation_address),check_in_date:nil(v.check_in_date),check_out_date:nil(v.check_out_date),accommodation_reference:nil(v.accommodation_reference),accommodation_notes:nil(v.accommodation_notes),companion_name:nil(v.companion_name),companion_relationship:nil(v.companion_relationship),companion_contact:nil(v.companion_contact),companion_notes:nil(v.companion_notes),updated_by:auth.userId};const{error}=await ctx.supabase.from('travel_plans').upsert(payload,{onConflict:'booking_id'});if(error)return{error:'save'};refresh(locale,v.booking_id);return{success:'saved'};}
export async function createTransportAction(_:OperationsActionState,f:FormData):Promise<OperationsActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,managerRoles);const p=transportSchema.safeParse(Object.fromEntries(f));if(!p.success)return{error:'invalid'};const ctx=await bookingFor(p.data.booking_id);if(!ctx)return{error:'unavailable'};const v=p.data;const{error}=await ctx.supabase.from('transport_arrangements').insert({...v,patient_id:ctx.booking.patient_id,pickup_at:new Date(v.pickup_at).toISOString(),provider_label:nil(v.provider_label),contact:nil(v.contact),notes:nil(v.notes),created_by:auth.userId});if(error)return{error:'save'};refresh(locale,v.booking_id);return{success:'saved'};}
