import { z } from 'zod';

const optional = (max:number) => z.string().trim().max(max).optional().default('');
export const appointmentSchema=z.object({booking_id:z.uuid(),appointment_id:z.uuid().optional(),appointment_type:z.enum(['CONSULTATION','PRE_TREATMENT_ASSESSMENT','TREATMENT_PROCEDURE','FOLLOW_UP','LAB_RADIOLOGY','DISCHARGE_FINAL_REVIEW']),scheduled_at:z.iso.datetime({local:true}),timezone:z.string().trim().min(1).max(80),duration_minutes:z.coerce.number().int().min(5).max(720),location_name:z.string().trim().min(2).max(300),location_details:optional(1000),instructions:optional(4000),provider_notes:optional(4000),status:z.enum(['REQUESTED','CONFIRMED','RESCHEDULED','COMPLETED','CANCELLED','NO_SHOW']).optional()});
export const journeyTypeSchema=z.object({booking_id:z.uuid(),journey_type:z.enum(['LOCAL_CARE','INTERNATIONAL_MEDICAL_TRAVEL']),journey_timezone:z.string().trim().min(1).max(80)});
export const invoiceSchema=z.object({booking_id:z.uuid(),currency:z.string().trim().toUpperCase().regex(/^[A-Z]{3}$/),due_date:z.iso.date().optional().or(z.literal('')),notes:optional(4000),description:z.string().trim().min(2).max(500),quantity:z.coerce.number().positive().max(100000),unit_amount:z.coerce.number().min(0).max(999999999)});
export const paymentSchema=z.object({invoice_id:z.uuid(),amount:z.coerce.number().positive().max(999999999),paid_at:z.iso.datetime({local:true}),method:z.enum(['BANK_TRANSFER','CASH','CARD_AT_PROVIDER','OTHER']),reference_number:optional(180),notes:optional(2000)});
export const travelSchema=z.object({booking_id:z.uuid(),arrival_at:z.string().optional(),departure_at:z.string().optional(),airline:optional(180),arrival_flight_number:optional(40),departure_flight_number:optional(40),origin_airport:optional(180),destination_airport:optional(180),arrival_terminal:optional(80),travel_notes:optional(3000),accommodation_mode:z.enum(['NOT_REQUIRED','SELF_ARRANGED','COORDINATED']),accommodation_name:optional(240),accommodation_address:optional(500),check_in_date:z.string().optional(),check_out_date:z.string().optional(),accommodation_reference:optional(180),accommodation_notes:optional(2000),companion_name:optional(180),companion_relationship:optional(120),companion_contact:optional(240),companion_notes:optional(1000)}).refine(v=>v.accommodation_mode!=='COORDINATED'||!!v.accommodation_name,{path:['accommodation_name'],message:'required'});
export const transportSchema=z.object({booking_id:z.uuid(),transport_type:z.enum(['AIRPORT_PICKUP','HOTEL_TO_HOSPITAL','HOSPITAL_TO_HOTEL','LOCAL_TRANSPORT','DISCHARGE_TRANSPORT']),pickup_at:z.iso.datetime({local:true}),pickup_location:z.string().trim().min(2).max(500),destination:z.string().trim().min(2).max(500),provider_label:optional(180),contact:optional(240),notes:optional(2000)});
