begin;

create type public.encounter_status as enum('OPEN','COMPLETED','CANCELLED');
create type public.prescription_status as enum('DRAFT','ISSUED','CANCELLED','COMPLETED');
create type public.clinical_priority as enum('ROUTINE','URGENT');
create type public.lab_order_status as enum('ORDERED','SCHEDULED','SAMPLE_COLLECTED','IN_PROGRESS','RESULT_AVAILABLE','REVIEWED','CANCELLED');
create type public.radiology_order_status as enum('ORDERED','SCHEDULED','IN_PROGRESS','RESULT_AVAILABLE','REVIEWED','CANCELLED');
create type public.follow_up_status as enum('PLANNED','SCHEDULED','COMPLETED','CANCELLED');
create type public.clinical_journey_status as enum('ACTIVE','CLINICAL_WORK_COMPLETED','FOLLOW_UP_PENDING','COMPLETED','CANCELLED');

alter table public.bookings add column clinical_status public.clinical_journey_status not null default 'ACTIVE';
create index bookings_clinical_status_idx on public.bookings(clinical_status,updated_at desc);

create table public.diagnostic_provider_memberships(
 id uuid primary key default gen_random_uuid(),provider_type public.provider_type not null check(provider_type in('RADIOLOGY_CENTER','MEDICAL_LABORATORY')),
 radiology_center_id uuid references public.radiology_centers(id) on delete cascade,medical_laboratory_id uuid references public.medical_laboratories(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,is_active boolean not null default true,created_at timestamptz not null default timezone('utc',now()),
 check(num_nonnulls(radiology_center_id,medical_laboratory_id)=1),check((provider_type='RADIOLOGY_CENTER' and radiology_center_id is not null)or(provider_type='MEDICAL_LABORATORY' and medical_laboratory_id is not null)),unique(provider_type,radiology_center_id,medical_laboratory_id,user_id));
create index diagnostic_memberships_user_idx on public.diagnostic_provider_memberships(user_id) where is_active;

create table public.clinical_encounters(
 id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,case_id uuid not null references public.medical_cases(id) on delete cascade,appointment_id uuid references public.appointments(id) on delete set null,
 patient_id uuid not null references auth.users(id) on delete restrict,doctor_id uuid not null references public.doctors(id) on delete restrict,encountered_at timestamptz not null,
 clinical_notes text check(clinical_notes is null or char_length(clinical_notes)<=12000),assessment text check(assessment is null or char_length(assessment)<=8000),diagnosis_summary text check(diagnosis_summary is null or char_length(diagnosis_summary)<=4000),treatment_progress text check(treatment_progress is null or char_length(treatment_progress)<=4000),next_steps text check(next_steps is null or char_length(next_steps)<=4000),follow_up_recommendation text check(follow_up_recommendation is null or char_length(follow_up_recommendation)<=2000),status public.encounter_status not null default 'OPEN',created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create index encounters_booking_time_idx on public.clinical_encounters(booking_id,encountered_at desc);create index encounters_doctor_status_idx on public.clinical_encounters(doctor_id,status,encountered_at desc);

create table public.prescriptions(
 id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,case_id uuid not null references public.medical_cases(id) on delete cascade,encounter_id uuid references public.clinical_encounters(id) on delete set null,appointment_id uuid references public.appointments(id) on delete set null,patient_id uuid not null references auth.users(id) on delete restrict,doctor_id uuid not null references public.doctors(id) on delete restrict,status public.prescription_status not null default 'DRAFT',issue_date date,instructions text check(instructions is null or char_length(instructions)<=4000),notes text check(notes is null or char_length(notes)<=4000),created_by uuid not null references auth.users(id) on delete restrict,issued_at timestamptz,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create index prescriptions_booking_idx on public.prescriptions(booking_id,created_at desc);create index prescriptions_patient_status_idx on public.prescriptions(patient_id,status,created_at desc);
create table public.prescription_items(id uuid primary key default gen_random_uuid(),prescription_id uuid not null references public.prescriptions(id) on delete cascade,medication_name text not null check(char_length(medication_name) between 2 and 240),strength text check(strength is null or char_length(strength)<=120),dosage text not null check(char_length(dosage) between 1 and 180),frequency text not null check(char_length(frequency) between 1 and 180),route text check(route is null or char_length(route)<=120),duration text check(duration is null or char_length(duration)<=180),instructions text check(instructions is null or char_length(instructions)<=1000),display_order smallint not null default 0,created_at timestamptz not null default timezone('utc',now()));
create index prescription_items_parent_idx on public.prescription_items(prescription_id,display_order);

create table public.lab_orders(
 id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,case_id uuid not null references public.medical_cases(id) on delete cascade,encounter_id uuid references public.clinical_encounters(id) on delete set null,appointment_id uuid references public.appointments(id) on delete set null,patient_id uuid not null references auth.users(id) on delete restrict,doctor_id uuid not null references public.doctors(id) on delete restrict,medical_laboratory_id uuid not null references public.medical_laboratories(id) on delete restrict,ordered_at timestamptz not null default timezone('utc',now()),priority public.clinical_priority not null default 'ROUTINE',clinical_instructions text check(clinical_instructions is null or char_length(clinical_instructions)<=4000),status public.lab_order_status not null default 'ORDERED',created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create index lab_orders_lab_status_idx on public.lab_orders(medical_laboratory_id,status,ordered_at desc);create index lab_orders_booking_idx on public.lab_orders(booking_id,ordered_at desc);
create table public.lab_order_tests(id uuid primary key default gen_random_uuid(),lab_order_id uuid not null references public.lab_orders(id) on delete cascade,test_name text not null check(char_length(test_name) between 2 and 240),instructions text check(instructions is null or char_length(instructions)<=1000),created_at timestamptz not null default timezone('utc',now()));
create index lab_tests_parent_idx on public.lab_order_tests(lab_order_id);
create table public.lab_results(id uuid primary key default gen_random_uuid(),lab_order_id uuid not null unique references public.lab_orders(id) on delete cascade,patient_id uuid not null references auth.users(id) on delete restrict,summary text check(summary is null or char_length(summary)<=8000),result_notes text check(result_notes is null or char_length(result_notes)<=8000),released_at timestamptz,released_by uuid references auth.users(id) on delete restrict,reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete restrict,created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));

create table public.radiology_orders(
 id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,case_id uuid not null references public.medical_cases(id) on delete cascade,encounter_id uuid references public.clinical_encounters(id) on delete set null,appointment_id uuid references public.appointments(id) on delete set null,patient_id uuid not null references auth.users(id) on delete restrict,doctor_id uuid not null references public.doctors(id) on delete restrict,radiology_center_id uuid not null references public.radiology_centers(id) on delete restrict,ordered_at timestamptz not null default timezone('utc',now()),study_name text not null check(char_length(study_name) between 2 and 240),modality text check(modality is null or char_length(modality)<=80),body_area text check(body_area is null or char_length(body_area)<=180),priority public.clinical_priority not null default 'ROUTINE',clinical_instructions text check(clinical_instructions is null or char_length(clinical_instructions)<=4000),status public.radiology_order_status not null default 'ORDERED',created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));
create index radiology_orders_center_status_idx on public.radiology_orders(radiology_center_id,status,ordered_at desc);create index radiology_orders_booking_idx on public.radiology_orders(booking_id,ordered_at desc);
create table public.radiology_results(id uuid primary key default gen_random_uuid(),radiology_order_id uuid not null unique references public.radiology_orders(id) on delete cascade,patient_id uuid not null references auth.users(id) on delete restrict,summary text check(summary is null or char_length(summary)<=8000),report_notes text check(report_notes is null or char_length(report_notes)<=8000),released_at timestamptz,released_by uuid references auth.users(id) on delete restrict,reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete restrict,created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()));

create table public.clinical_result_documents(id uuid primary key default gen_random_uuid(),lab_result_id uuid references public.lab_results(id) on delete cascade,radiology_result_id uuid references public.radiology_results(id) on delete cascade,patient_id uuid not null references auth.users(id) on delete cascade,object_path text not null unique check(object_path !~ '(^|/)\.\.(/|$)'),original_filename text not null check(char_length(original_filename) between 1 and 240),mime_type text not null check(mime_type in('application/pdf','image/jpeg','image/png','image/webp','application/dicom')),file_size_bytes bigint not null check(file_size_bytes between 1 and 26214400),uploaded_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),check(num_nonnulls(lab_result_id,radiology_result_id)=1));
create index result_documents_lab_idx on public.clinical_result_documents(lab_result_id);create index result_documents_radiology_idx on public.clinical_result_documents(radiology_result_id);

create table public.clinical_follow_ups(id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,encounter_id uuid references public.clinical_encounters(id) on delete set null,appointment_id uuid references public.appointments(id) on delete set null,patient_id uuid not null references auth.users(id) on delete restrict,doctor_id uuid not null references public.doctors(id) on delete restrict,recommended_date date,window_end_date date,recommendation text not null check(char_length(recommendation) between 2 and 2000),completion_notes text check(completion_notes is null or char_length(completion_notes)<=4000),status public.follow_up_status not null default 'PLANNED',created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default timezone('utc',now()),updated_at timestamptz not null default timezone('utc',now()),check(window_end_date is null or recommended_date is null or window_end_date>=recommended_date));
create index followups_patient_status_idx on public.clinical_follow_ups(patient_id,status,recommended_date);create index followups_doctor_status_idx on public.clinical_follow_ups(doctor_id,status,recommended_date);

create function public.is_diagnostic_member(kind public.provider_type,target_id uuid) returns boolean language sql stable security definer set search_path='' as $$select case when kind='MEDICAL_LABORATORY' then public.is_medical_laboratory_owner(target_id) or exists(select 1 from public.diagnostic_provider_memberships where provider_type=kind and medical_laboratory_id=target_id and user_id=auth.uid() and is_active) when kind='RADIOLOGY_CENTER' then public.is_radiology_center_owner(target_id) or exists(select 1 from public.diagnostic_provider_memberships where provider_type=kind and radiology_center_id=target_id and user_id=auth.uid() and is_active) else false end$$;
create function public.can_manage_clinical_booking(target_booking uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_booking_doctor(target_booking) or public.has_admin_privilege('clinical.support')$$;

create function public.protect_doctor_clinical_row() returns trigger language plpgsql set search_path='' as $$declare d jsonb:=to_jsonb(new);b public.bookings;begin if current_user in('postgres','supabase_admin','service_role') or coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' then return new;end if;select * into b from public.bookings where id=(d->>'booking_id')::uuid;if b.id is null or (d->>'patient_id')::uuid<>b.patient_id or (d ? 'case_id' and (d->>'case_id')::uuid<>b.case_id) or (d->>'doctor_id')::uuid is distinct from b.doctor_id or not public.can_manage_clinical_booking(b.id) then raise exception 'clinical scope mismatch';end if;if tg_op='INSERT' and (d->>'created_by')::uuid<>auth.uid() then raise exception 'clinical creator mismatch';end if;if tg_op='UPDATE' and ((to_jsonb(new)->>'booking_id') is distinct from(to_jsonb(old)->>'booking_id') or(to_jsonb(new)->>'patient_id') is distinct from(to_jsonb(old)->>'patient_id') or(to_jsonb(new)->>'doctor_id') is distinct from(to_jsonb(old)->>'doctor_id') or (d ? 'case_id' and (to_jsonb(new)->>'case_id') is distinct from(to_jsonb(old)->>'case_id'))) then raise exception 'clinical relationship fields are immutable';end if;return new;end$$;
create function public.protect_prescription() returns trigger language plpgsql set search_path='' as $$begin if tg_op='INSERT' then return new;end if;if old.status<>'DRAFT' and (new.instructions is distinct from old.instructions or new.notes is distinct from old.notes) then raise exception 'issued prescription is locked';end if;if new.status is distinct from old.status and not((old.status='DRAFT' and new.status in('ISSUED','CANCELLED'))or(old.status='ISSUED' and new.status in('COMPLETED','CANCELLED')))then raise exception 'invalid prescription transition';end if;if new.status='ISSUED' and old.status<>'ISSUED' then new.issued_at:=timezone('utc',now());new.issue_date:=coalesce(new.issue_date,current_date);end if;return new;end$$;
create function public.protect_lab_order() returns trigger language plpgsql set search_path='' as $$declare b public.bookings;begin if current_user in('postgres','supabase_admin','service_role') or coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' then return new;end if;select * into b from public.bookings where id=new.booking_id;if new.patient_id<>b.patient_id or new.case_id<>b.case_id or new.doctor_id is distinct from b.doctor_id then raise exception 'lab order scope mismatch';end if;if tg_op='INSERT' then if not public.can_manage_clinical_booking(new.booking_id) or new.created_by<>auth.uid() or new.status<>'ORDERED' then raise exception 'lab order creation denied';end if;else if new.booking_id<>old.booking_id or new.patient_id<>old.patient_id or new.doctor_id<>old.doctor_id or new.medical_laboratory_id<>old.medical_laboratory_id then raise exception 'lab relationships immutable';end if;if public.is_diagnostic_member('MEDICAL_LABORATORY',old.medical_laboratory_id) then if new.status is distinct from old.status and not((old.status='ORDERED' and new.status in('SCHEDULED','CANCELLED'))or(old.status='SCHEDULED' and new.status in('SAMPLE_COLLECTED','CANCELLED'))or(old.status='SAMPLE_COLLECTED' and new.status='IN_PROGRESS'or old.status='IN_PROGRESS' and new.status='RESULT_AVAILABLE'))then raise exception 'invalid lab transition';end if;if new.clinical_instructions is distinct from old.clinical_instructions then raise exception 'laboratory cannot edit doctor instructions';end if;elsif not public.can_manage_clinical_booking(old.booking_id) then raise exception 'lab update denied';end if;end if;return new;end$$;
create function public.protect_radiology_order() returns trigger language plpgsql set search_path='' as $$declare b public.bookings;begin if current_user in('postgres','supabase_admin','service_role') or coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' then return new;end if;select * into b from public.bookings where id=new.booking_id;if new.patient_id<>b.patient_id or new.case_id<>b.case_id or new.doctor_id is distinct from b.doctor_id then raise exception 'radiology order scope mismatch';end if;if tg_op='INSERT' then if not public.can_manage_clinical_booking(new.booking_id) or new.created_by<>auth.uid() or new.status<>'ORDERED' then raise exception 'radiology creation denied';end if;else if new.booking_id<>old.booking_id or new.patient_id<>old.patient_id or new.doctor_id<>old.doctor_id or new.radiology_center_id<>old.radiology_center_id then raise exception 'radiology relationships immutable';end if;if public.is_diagnostic_member('RADIOLOGY_CENTER',old.radiology_center_id) then if new.status is distinct from old.status and not((old.status='ORDERED' and new.status in('SCHEDULED','CANCELLED'))or(old.status='SCHEDULED' and new.status in('IN_PROGRESS','CANCELLED'))or(old.status='IN_PROGRESS' and new.status='RESULT_AVAILABLE'))then raise exception 'invalid radiology transition';end if;if new.clinical_instructions is distinct from old.clinical_instructions then raise exception 'radiology cannot edit doctor instructions';end if;elsif not public.can_manage_clinical_booking(old.booking_id) then raise exception 'radiology update denied';end if;end if;return new;end$$;

create function public.can_read_lab_result(r public.lab_results) returns boolean language sql stable security definer set search_path='' as $$select (r.patient_id=auth.uid() and r.released_at is not null)or exists(select 1 from public.lab_orders o where o.id=r.lab_order_id and(public.can_manage_clinical_booking(o.booking_id)or public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)))$$;
create function public.can_read_radiology_result(r public.radiology_results) returns boolean language sql stable security definer set search_path='' as $$select (r.patient_id=auth.uid() and r.released_at is not null)or exists(select 1 from public.radiology_orders o where o.id=r.radiology_order_id and(public.can_manage_clinical_booking(o.booking_id)or public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id)))$$;
create function public.protect_lab_result() returns trigger language plpgsql set search_path='' as $$declare o public.lab_orders;begin select * into o from public.lab_orders where id=new.lab_order_id;if new.patient_id<>o.patient_id then raise exception 'lab result scope mismatch';end if;if tg_op='INSERT' then if not public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id) or new.created_by<>auth.uid() then raise exception 'lab result creation denied';end if;else if new.lab_order_id<>old.lab_order_id or new.patient_id<>old.patient_id or new.created_by<>old.created_by then raise exception 'lab result relationships immutable';end if;if public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id) then if new.reviewed_at is distinct from old.reviewed_at or new.reviewed_by is distinct from old.reviewed_by then raise exception 'laboratory cannot mark doctor review';end if;if new.released_at is not null and old.released_at is null then new.released_by:=auth.uid();end if;elsif public.can_manage_clinical_booking(o.booking_id) then if new.summary is distinct from old.summary or new.result_notes is distinct from old.result_notes or new.released_at is distinct from old.released_at then raise exception 'doctor cannot edit laboratory result';end if;if new.reviewed_at is not null and old.reviewed_at is null then new.reviewed_by:=auth.uid();update public.lab_orders set status='REVIEWED' where id=o.id and status='RESULT_AVAILABLE';end if;else raise exception 'lab result update denied';end if;end if;return new;end$$;
create function public.protect_radiology_result() returns trigger language plpgsql set search_path='' as $$declare o public.radiology_orders;begin select * into o from public.radiology_orders where id=new.radiology_order_id;if new.patient_id<>o.patient_id then raise exception 'radiology result scope mismatch';end if;if tg_op='INSERT' then if not public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id) or new.created_by<>auth.uid() then raise exception 'radiology result creation denied';end if;else if new.radiology_order_id<>old.radiology_order_id or new.patient_id<>old.patient_id or new.created_by<>old.created_by then raise exception 'radiology result relationships immutable';end if;if public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id) then if new.reviewed_at is distinct from old.reviewed_at or new.reviewed_by is distinct from old.reviewed_by then raise exception 'radiology cannot mark doctor review';end if;if new.released_at is not null and old.released_at is null then new.released_by:=auth.uid();end if;elsif public.can_manage_clinical_booking(o.booking_id) then if new.summary is distinct from old.summary or new.report_notes is distinct from old.report_notes or new.released_at is distinct from old.released_at then raise exception 'doctor cannot edit radiology result';end if;if new.reviewed_at is not null and old.reviewed_at is null then new.reviewed_by:=auth.uid();update public.radiology_orders set status='REVIEWED' where id=o.id and status='RESULT_AVAILABLE';end if;else raise exception 'radiology result update denied';end if;end if;return new;end$$;

create function public.clinical_event() returns trigger language plpgsql security definer set search_path='' as $$declare n jsonb:=to_jsonb(new);o jsonb;event text;booking uuid;patient uuid;begin if tg_op='UPDATE'then o:=to_jsonb(old);else o:='{}';end if;booking:=(n->>'booking_id')::uuid;patient:=(n->>'patient_id')::uuid;if tg_table_name='prescriptions' and n->>'status'='ISSUED' and n->>'status' is distinct from o->>'status'then event:='prescription.issued';elsif tg_table_name='lab_orders' and(tg_op='INSERT'or n->>'status'is distinct from o->>'status')then event:='lab.'||lower(n->>'status');elsif tg_table_name='radiology_orders' and(tg_op='INSERT'or n->>'status'is distinct from o->>'status')then event:='radiology.'||lower(n->>'status');elsif tg_table_name='clinical_follow_ups' and(tg_op='INSERT'or n->>'status'is distinct from o->>'status')then event:='follow_up.'||lower(n->>'status');elsif tg_table_name='clinical_encounters' and n->>'status'='COMPLETED' and n->>'status'is distinct from o->>'status'then event:='consultation.completed';else return new;end if;insert into public.journey_events(booking_id,event_type,related_entity_type,related_entity_id,status_label,created_by)values(booking,event,tg_table_name,(n->>'id')::uuid,n->>'status',auth.uid());if event in('prescription.issued','lab.ordered','lab.scheduled','lab.result_available','radiology.ordered','radiology.result_available','follow_up.planned','follow_up.scheduled')then insert into public.notifications(recipient_id,type,title_key,message_key,related_entity_type,related_entity_id)values(patient,event,'part6.notifications.'||replace(event,'.','')||'Title','part6.notifications.'||replace(event,'.','')||'Message','booking',booking);end if;return new;end$$;
create function public.result_release_event() returns trigger language plpgsql security definer set search_path='' as $$declare booking uuid;kind text;begin if new.released_at is not null and old.released_at is null then if tg_table_name='lab_results'then select booking_id into booking from public.lab_orders where id=new.lab_order_id;kind:='lab.result_released';else select booking_id into booking from public.radiology_orders where id=new.radiology_order_id;kind:='radiology.result_released';end if;insert into public.journey_events(booking_id,event_type,related_entity_type,related_entity_id,status_label,created_by)values(booking,kind,tg_table_name,new.id,'RELEASED',auth.uid());insert into public.notifications(recipient_id,type,title_key,message_key,related_entity_type,related_entity_id)values(new.patient_id,kind,'part6.notifications.'||replace(kind,'.','')||'Title','part6.notifications.'||replace(kind,'.','')||'Message','booking',booking);end if;return new;end$$;

create function public.protect_clinical_result_document() returns trigger language plpgsql set search_path='' as $$declare expected_patient uuid;expected_kind text;expected_result uuid;parts text[];allowed boolean:=false;begin if tg_op='UPDATE' then raise exception 'clinical result document metadata is immutable';end if;if new.uploaded_by<>auth.uid() then raise exception 'clinical result uploader mismatch';end if;if new.lab_result_id is not null then select r.patient_id,public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id) into expected_patient,allowed from public.lab_results r join public.lab_orders o on o.id=r.lab_order_id where r.id=new.lab_result_id;expected_kind:='lab';expected_result:=new.lab_result_id;else select r.patient_id,public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id) into expected_patient,allowed from public.radiology_results r join public.radiology_orders o on o.id=r.radiology_order_id where r.id=new.radiology_result_id;expected_kind:='radiology';expected_result:=new.radiology_result_id;end if;parts:=storage.foldername(new.object_path);if not allowed or new.patient_id is distinct from expected_patient or array_length(parts,1)<>3 or parts[1]<>expected_patient::text or parts[2]<>expected_kind or parts[3]<>expected_result::text or new.object_path!~('^'||expected_patient::text||'/'||expected_kind||'/'||expected_result::text||'/[A-Za-z0-9][A-Za-z0-9._-]{0,239}$') then raise exception 'clinical result document scope mismatch';end if;return new;end$$;

create function public.protect_booking_clinical_status() returns trigger language plpgsql set search_path='' as $$begin if new.clinical_status is not distinct from old.clinical_status then return new;end if;if current_user not in('postgres','supabase_admin','service_role') and coalesce(current_setting('request.jwt.claim.role',true),'')<>'service_role' and not public.can_manage_clinical_booking(old.id) then raise exception 'clinical journey status change is not permitted';end if;if not((old.clinical_status='ACTIVE' and new.clinical_status in('CLINICAL_WORK_COMPLETED','FOLLOW_UP_PENDING','CANCELLED'))or(old.clinical_status='CLINICAL_WORK_COMPLETED' and new.clinical_status in('FOLLOW_UP_PENDING','COMPLETED','CANCELLED'))or(old.clinical_status='FOLLOW_UP_PENDING' and new.clinical_status in('COMPLETED','CANCELLED')))then raise exception 'invalid clinical journey transition';end if;return new;end$$;
create function public.booking_clinical_event() returns trigger language plpgsql security definer set search_path='' as $$declare event text;begin if new.clinical_status is not distinct from old.clinical_status then return new;end if;event:=case new.clinical_status when 'CLINICAL_WORK_COMPLETED' then 'treatment.completed' when 'FOLLOW_UP_PENDING' then 'follow_up.pending' when 'COMPLETED' then 'journey.completed' when 'CANCELLED' then 'journey.cancelled' else null end;if event is null then return new;end if;insert into public.journey_events(booking_id,event_type,related_entity_type,related_entity_id,status_label,created_by)values(new.id,event,'bookings',new.id,new.clinical_status::text,auth.uid());if new.clinical_status in('FOLLOW_UP_PENDING','COMPLETED')then insert into public.notifications(recipient_id,type,title_key,message_key,related_entity_type,related_entity_id)values(new.patient_id,event,'part6.notifications.'||replace(event,'.','')||'Title','part6.notifications.'||replace(event,'.','')||'Message','booking',new.id);end if;return new;end$$;

alter table public.diagnostic_provider_memberships enable row level security;alter table public.clinical_encounters enable row level security;alter table public.prescriptions enable row level security;alter table public.prescription_items enable row level security;alter table public.lab_orders enable row level security;alter table public.lab_order_tests enable row level security;alter table public.lab_results enable row level security;alter table public.radiology_orders enable row level security;alter table public.radiology_results enable row level security;alter table public.clinical_result_documents enable row level security;alter table public.clinical_follow_ups enable row level security;
create policy diagnostic_members_scoped on public.diagnostic_provider_memberships for select to authenticated using(user_id=auth.uid()or public.is_diagnostic_member(provider_type,coalesce(radiology_center_id,medical_laboratory_id))or public.has_admin_privilege('clinical.support'));create policy diagnostic_members_manage on public.diagnostic_provider_memberships for all to authenticated using(public.is_diagnostic_member(provider_type,coalesce(radiology_center_id,medical_laboratory_id))or public.has_admin_privilege('clinical.support'))with check(public.is_diagnostic_member(provider_type,coalesce(radiology_center_id,medical_laboratory_id))or public.has_admin_privilege('clinical.support'));
create policy encounters_doctor_only on public.clinical_encounters for all to authenticated using(public.can_manage_clinical_booking(booking_id))with check(public.can_manage_clinical_booking(booking_id));
create policy prescriptions_read on public.prescriptions for select to authenticated using((patient_id=auth.uid()and status in('ISSUED','COMPLETED'))or public.can_manage_clinical_booking(booking_id));create policy prescriptions_manage on public.prescriptions for all to authenticated using(public.can_manage_clinical_booking(booking_id))with check(public.can_manage_clinical_booking(booking_id));
create policy prescription_items_read on public.prescription_items for select to authenticated using(exists(select 1 from public.prescriptions p where p.id=prescription_id and((p.patient_id=auth.uid()and p.status in('ISSUED','COMPLETED'))or public.can_manage_clinical_booking(p.booking_id))));create policy prescription_items_manage on public.prescription_items for all to authenticated using(exists(select 1 from public.prescriptions p where p.id=prescription_id and p.status='DRAFT'and public.can_manage_clinical_booking(p.booking_id)))with check(exists(select 1 from public.prescriptions p where p.id=prescription_id and p.status='DRAFT'and public.can_manage_clinical_booking(p.booking_id)));
create policy lab_orders_read on public.lab_orders for select to authenticated using(patient_id=auth.uid()or public.can_manage_clinical_booking(booking_id)or public.is_diagnostic_member('MEDICAL_LABORATORY',medical_laboratory_id));create policy lab_orders_insert on public.lab_orders for insert to authenticated with check(public.can_manage_clinical_booking(booking_id));create policy lab_orders_update on public.lab_orders for update to authenticated using(public.can_manage_clinical_booking(booking_id)or public.is_diagnostic_member('MEDICAL_LABORATORY',medical_laboratory_id))with check(public.can_manage_clinical_booking(booking_id)or public.is_diagnostic_member('MEDICAL_LABORATORY',medical_laboratory_id));
create policy lab_tests_read on public.lab_order_tests for select to authenticated using(exists(select 1 from public.lab_orders o where o.id=lab_order_id and(o.patient_id=auth.uid()or public.can_manage_clinical_booking(o.booking_id)or public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id))));create policy lab_tests_doctor_write on public.lab_order_tests for all to authenticated using(exists(select 1 from public.lab_orders o where o.id=lab_order_id and o.status='ORDERED'and public.can_manage_clinical_booking(o.booking_id)))with check(exists(select 1 from public.lab_orders o where o.id=lab_order_id and o.status='ORDERED'and public.can_manage_clinical_booking(o.booking_id)));
create policy lab_results_read on public.lab_results for select to authenticated using(public.can_read_lab_result(lab_results));create policy lab_results_insert on public.lab_results for insert to authenticated with check(exists(select 1 from public.lab_orders o where o.id=lab_order_id and public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)));create policy lab_results_update on public.lab_results for update to authenticated using(public.can_read_lab_result(lab_results))with check(public.can_read_lab_result(lab_results));
create policy radiology_orders_read on public.radiology_orders for select to authenticated using(patient_id=auth.uid()or public.can_manage_clinical_booking(booking_id)or public.is_diagnostic_member('RADIOLOGY_CENTER',radiology_center_id));create policy radiology_orders_insert on public.radiology_orders for insert to authenticated with check(public.can_manage_clinical_booking(booking_id));create policy radiology_orders_update on public.radiology_orders for update to authenticated using(public.can_manage_clinical_booking(booking_id)or public.is_diagnostic_member('RADIOLOGY_CENTER',radiology_center_id))with check(public.can_manage_clinical_booking(booking_id)or public.is_diagnostic_member('RADIOLOGY_CENTER',radiology_center_id));
create policy radiology_results_read on public.radiology_results for select to authenticated using(public.can_read_radiology_result(radiology_results));create policy radiology_results_insert on public.radiology_results for insert to authenticated with check(exists(select 1 from public.radiology_orders o where o.id=radiology_order_id and public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id)));create policy radiology_results_update on public.radiology_results for update to authenticated using(public.can_read_radiology_result(radiology_results))with check(public.can_read_radiology_result(radiology_results));
create policy result_documents_read on public.clinical_result_documents for select to authenticated using((lab_result_id is not null and exists(select 1 from public.lab_results r where r.id=lab_result_id and public.can_read_lab_result(r)))or(radiology_result_id is not null and exists(select 1 from public.radiology_results r where r.id=radiology_result_id and public.can_read_radiology_result(r))));create policy result_documents_insert on public.clinical_result_documents for insert to authenticated with check((lab_result_id is not null and exists(select 1 from public.lab_results r join public.lab_orders o on o.id=r.lab_order_id where r.id=lab_result_id and public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)))or(radiology_result_id is not null and exists(select 1 from public.radiology_results r join public.radiology_orders o on o.id=r.radiology_order_id where r.id=radiology_result_id and public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id))));
create policy followups_read on public.clinical_follow_ups for select to authenticated using(patient_id=auth.uid()or public.can_manage_clinical_booking(booking_id));create policy followups_manage on public.clinical_follow_ups for all to authenticated using(public.can_manage_clinical_booking(booking_id))with check(public.can_manage_clinical_booking(booking_id));

create function public.can_access_clinical_result_object(object_name text,write_access boolean default false)returns boolean language plpgsql stable security definer set search_path='' as $$declare p text[];patient uuid;kind text;result uuid;begin p:=storage.foldername(object_name);if array_length(p,1)<3 then return false;end if;begin patient:=p[1]::uuid;kind:=p[2];result:=p[3]::uuid;exception when invalid_text_representation then return false;end;if kind='lab'then return exists(select 1 from public.lab_results r join public.lab_orders o on o.id=r.lab_order_id where r.id=result and r.patient_id=patient and(case when write_access then public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)else public.can_read_lab_result(r)end));elsif kind='radiology'then return exists(select 1 from public.radiology_results r join public.radiology_orders o on o.id=r.radiology_order_id where r.id=result and r.patient_id=patient and(case when write_access then public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id)else public.can_read_radiology_result(r)end));end if;return false;end$$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('clinical-results','clinical-results',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp','application/dicom'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy clinical_results_storage_read on storage.objects for select to authenticated using(bucket_id='clinical-results'and public.can_access_clinical_result_object(name,false));create policy clinical_results_storage_insert on storage.objects for insert to authenticated with check(bucket_id='clinical-results'and public.can_access_clinical_result_object(name,true));create policy clinical_results_storage_delete on storage.objects for delete to authenticated using(bucket_id='clinical-results'and public.can_access_clinical_result_object(name,true));

create trigger encounters_protect before insert or update on public.clinical_encounters for each row execute function public.protect_doctor_clinical_row();create trigger encounters_updated before update on public.clinical_encounters for each row execute function public.set_updated_at();create trigger encounters_event after insert or update on public.clinical_encounters for each row execute function public.clinical_event();
create trigger prescriptions_scope before insert or update on public.prescriptions for each row execute function public.protect_doctor_clinical_row();create trigger prescriptions_protect before insert or update on public.prescriptions for each row execute function public.protect_prescription();create trigger prescriptions_updated before update on public.prescriptions for each row execute function public.set_updated_at();create trigger prescriptions_event after insert or update on public.prescriptions for each row execute function public.clinical_event();
create trigger lab_orders_protect before insert or update on public.lab_orders for each row execute function public.protect_lab_order();create trigger lab_orders_updated before update on public.lab_orders for each row execute function public.set_updated_at();create trigger lab_orders_event after insert or update on public.lab_orders for each row execute function public.clinical_event();
create trigger radiology_orders_protect before insert or update on public.radiology_orders for each row execute function public.protect_radiology_order();create trigger radiology_orders_updated before update on public.radiology_orders for each row execute function public.set_updated_at();create trigger radiology_orders_event after insert or update on public.radiology_orders for each row execute function public.clinical_event();
create trigger lab_results_protect before insert or update on public.lab_results for each row execute function public.protect_lab_result();create trigger lab_results_updated before update on public.lab_results for each row execute function public.set_updated_at();create trigger lab_results_release after update on public.lab_results for each row execute function public.result_release_event();create trigger radiology_results_protect before insert or update on public.radiology_results for each row execute function public.protect_radiology_result();create trigger radiology_results_updated before update on public.radiology_results for each row execute function public.set_updated_at();create trigger radiology_results_release after update on public.radiology_results for each row execute function public.result_release_event();
create trigger followups_protect before insert or update on public.clinical_follow_ups for each row execute function public.protect_doctor_clinical_row();create trigger followups_updated before update on public.clinical_follow_ups for each row execute function public.set_updated_at();create trigger followups_event after insert or update on public.clinical_follow_ups for each row execute function public.clinical_event();
create trigger result_documents_protect before insert or update on public.clinical_result_documents for each row execute function public.protect_clinical_result_document();
create trigger bookings_clinical_protect before update on public.bookings for each row execute function public.protect_booking_clinical_status();create trigger bookings_clinical_event after update on public.bookings for each row execute function public.booking_clinical_event();
create trigger encounters_audit after insert or update or delete on public.clinical_encounters for each row execute function public.audit_admin_change();create trigger prescriptions_audit after insert or update or delete on public.prescriptions for each row execute function public.audit_admin_change();create trigger lab_orders_audit after insert or update or delete on public.lab_orders for each row execute function public.audit_admin_change();create trigger lab_results_audit after insert or update or delete on public.lab_results for each row execute function public.audit_admin_change();create trigger radiology_orders_audit after insert or update or delete on public.radiology_orders for each row execute function public.audit_admin_change();create trigger radiology_results_audit after insert or update or delete on public.radiology_results for each row execute function public.audit_admin_change();create trigger followups_audit after insert or update or delete on public.clinical_follow_ups for each row execute function public.audit_admin_change();create trigger result_documents_audit after insert or update or delete on public.clinical_result_documents for each row execute function public.audit_admin_change();

revoke all on function public.is_diagnostic_member(public.provider_type,uuid),public.can_manage_clinical_booking(uuid),public.can_read_lab_result(public.lab_results),public.can_read_radiology_result(public.radiology_results),public.can_access_clinical_result_object(text,boolean) from public;grant execute on function public.is_diagnostic_member(public.provider_type,uuid),public.can_manage_clinical_booking(uuid),public.can_read_lab_result(public.lab_results),public.can_read_radiology_result(public.radiology_results),public.can_access_clinical_result_object(text,boolean) to authenticated;
grant select on public.diagnostic_provider_memberships,public.clinical_encounters,public.prescriptions,public.prescription_items,public.lab_orders,public.lab_order_tests,public.lab_results,public.radiology_orders,public.radiology_results,public.clinical_result_documents,public.clinical_follow_ups to authenticated;grant insert,update on public.clinical_encounters,public.prescriptions,public.prescription_items,public.lab_orders,public.lab_order_tests,public.lab_results,public.radiology_orders,public.radiology_results,public.clinical_result_documents,public.clinical_follow_ups,public.diagnostic_provider_memberships to authenticated;grant delete on public.prescription_items,public.lab_order_tests,public.clinical_result_documents,public.diagnostic_provider_memberships to authenticated;

commit;
