begin;

create function public.clinical_scope_matches(target_booking uuid,target_patient uuid,target_case uuid,target_doctor uuid)
returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.bookings b where b.id=target_booking and b.patient_id=target_patient and(target_case is null or b.case_id=target_case)and b.doctor_id is not distinct from target_doctor)
$$;

create or replace function public.protect_doctor_clinical_row() returns trigger language plpgsql set search_path='' as $$
declare d jsonb:=to_jsonb(new);
begin
 if current_user in('postgres','supabase_admin','service_role') or coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' then return new;end if;
 if not public.clinical_scope_matches((d->>'booking_id')::uuid,(d->>'patient_id')::uuid,case when d ? 'case_id'then(d->>'case_id')::uuid else null end,(d->>'doctor_id')::uuid) or not public.can_manage_clinical_booking((d->>'booking_id')::uuid)then raise exception 'clinical scope mismatch';end if;
 if tg_op='INSERT' and(d->>'created_by')::uuid<>auth.uid()then raise exception 'clinical creator mismatch';end if;
 if tg_op='UPDATE' and((to_jsonb(new)->>'booking_id')is distinct from(to_jsonb(old)->>'booking_id')or(to_jsonb(new)->>'patient_id')is distinct from(to_jsonb(old)->>'patient_id')or(to_jsonb(new)->>'doctor_id')is distinct from(to_jsonb(old)->>'doctor_id')or(d ? 'case_id'and(to_jsonb(new)->>'case_id')is distinct from(to_jsonb(old)->>'case_id')))then raise exception 'clinical relationship fields are immutable';end if;
 return new;
end$$;

create or replace function public.protect_lab_order() returns trigger language plpgsql set search_path='' as $$
begin
 if current_user in('postgres','supabase_admin','service_role') or coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' then return new;end if;
 if not public.clinical_scope_matches(new.booking_id,new.patient_id,new.case_id,new.doctor_id)then raise exception 'lab order scope mismatch';end if;
 if tg_op='INSERT' then if not public.can_manage_clinical_booking(new.booking_id)or new.created_by<>auth.uid()or new.status<>'ORDERED'then raise exception 'lab order creation denied';end if;
 else
  if new.booking_id<>old.booking_id or new.patient_id<>old.patient_id or new.doctor_id<>old.doctor_id or new.medical_laboratory_id<>old.medical_laboratory_id then raise exception 'lab relationships immutable';end if;
  if public.is_diagnostic_member('MEDICAL_LABORATORY',old.medical_laboratory_id)then
   if new.status is distinct from old.status and not((old.status='ORDERED'and new.status in('SCHEDULED','CANCELLED'))or(old.status='SCHEDULED'and new.status in('SAMPLE_COLLECTED','CANCELLED'))or(old.status='SAMPLE_COLLECTED'and new.status='IN_PROGRESS'or old.status='IN_PROGRESS'and new.status='RESULT_AVAILABLE'))then raise exception 'invalid lab transition';end if;
   if new.clinical_instructions is distinct from old.clinical_instructions then raise exception 'laboratory cannot edit doctor instructions';end if;
  elsif public.can_manage_clinical_booking(old.booking_id)then
   if new.status is distinct from old.status and not((old.status in('ORDERED','SCHEDULED')and new.status='CANCELLED')or(old.status='RESULT_AVAILABLE'and new.status='REVIEWED'))then raise exception 'doctor cannot manage laboratory processing status';end if;
  else raise exception 'lab update denied';end if;
 end if;return new;
end$$;

create or replace function public.protect_radiology_order() returns trigger language plpgsql set search_path='' as $$
begin
 if current_user in('postgres','supabase_admin','service_role') or coalesce(current_setting('request.jwt.claim.role',true),'')='service_role' then return new;end if;
 if not public.clinical_scope_matches(new.booking_id,new.patient_id,new.case_id,new.doctor_id)then raise exception 'radiology order scope mismatch';end if;
 if tg_op='INSERT' then if not public.can_manage_clinical_booking(new.booking_id)or new.created_by<>auth.uid()or new.status<>'ORDERED'then raise exception 'radiology creation denied';end if;
 else
  if new.booking_id<>old.booking_id or new.patient_id<>old.patient_id or new.doctor_id<>old.doctor_id or new.radiology_center_id<>old.radiology_center_id then raise exception 'radiology relationships immutable';end if;
  if public.is_diagnostic_member('RADIOLOGY_CENTER',old.radiology_center_id)then
   if new.status is distinct from old.status and not((old.status='ORDERED'and new.status in('SCHEDULED','CANCELLED'))or(old.status='SCHEDULED'and new.status in('IN_PROGRESS','CANCELLED'))or(old.status='IN_PROGRESS'and new.status='RESULT_AVAILABLE'))then raise exception 'invalid radiology transition';end if;
   if new.clinical_instructions is distinct from old.clinical_instructions then raise exception 'radiology cannot edit doctor instructions';end if;
  elsif public.can_manage_clinical_booking(old.booking_id)then
   if new.status is distinct from old.status and not((old.status in('ORDERED','SCHEDULED')and new.status='CANCELLED')or(old.status='RESULT_AVAILABLE'and new.status='REVIEWED'))then raise exception 'doctor cannot manage radiology processing status';end if;
  else raise exception 'radiology update denied';end if;
 end if;return new;
end$$;

create or replace function public.protect_lab_result() returns trigger language plpgsql set search_path='' as $$declare o public.lab_orders;begin select * into o from public.lab_orders where id=new.lab_order_id;if new.patient_id<>o.patient_id then raise exception 'lab result scope mismatch';end if;if tg_op='INSERT' then if not public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)or new.created_by<>auth.uid()or o.status not in('IN_PROGRESS','RESULT_AVAILABLE')then raise exception 'lab result creation denied';end if;else if new.lab_order_id<>old.lab_order_id or new.patient_id<>old.patient_id or new.created_by<>old.created_by then raise exception 'lab result relationships immutable';end if;if public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)then if new.reviewed_at is distinct from old.reviewed_at or new.reviewed_by is distinct from old.reviewed_by then raise exception 'laboratory cannot mark doctor review';end if;if old.released_at is not null and(new.released_at is distinct from old.released_at or new.released_by is distinct from old.released_by)then raise exception 'released laboratory result is immutable';end if;if new.released_at is not null and old.released_at is null then if o.status<>'RESULT_AVAILABLE'then raise exception 'laboratory result is not available';end if;new.released_by:=auth.uid();end if;elsif public.can_manage_clinical_booking(o.booking_id)then if new.summary is distinct from old.summary or new.result_notes is distinct from old.result_notes or new.released_at is distinct from old.released_at or new.released_by is distinct from old.released_by then raise exception 'doctor cannot edit laboratory result';end if;if old.reviewed_at is not null and(new.reviewed_at is distinct from old.reviewed_at or new.reviewed_by is distinct from old.reviewed_by)then raise exception 'laboratory review is immutable';end if;if new.reviewed_at is not null and old.reviewed_at is null then new.reviewed_by:=auth.uid();update public.lab_orders set status='REVIEWED'where id=o.id and status='RESULT_AVAILABLE';end if;else raise exception 'lab result update denied';end if;end if;return new;end$$;
create or replace function public.protect_radiology_result() returns trigger language plpgsql set search_path='' as $$declare o public.radiology_orders;begin select * into o from public.radiology_orders where id=new.radiology_order_id;if new.patient_id<>o.patient_id then raise exception 'radiology result scope mismatch';end if;if tg_op='INSERT' then if not public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id)or new.created_by<>auth.uid()or o.status not in('IN_PROGRESS','RESULT_AVAILABLE')then raise exception 'radiology result creation denied';end if;else if new.radiology_order_id<>old.radiology_order_id or new.patient_id<>old.patient_id or new.created_by<>old.created_by then raise exception 'radiology result relationships immutable';end if;if public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id)then if new.reviewed_at is distinct from old.reviewed_at or new.reviewed_by is distinct from old.reviewed_by then raise exception 'radiology cannot mark doctor review';end if;if old.released_at is not null and(new.released_at is distinct from old.released_at or new.released_by is distinct from old.released_by)then raise exception 'released radiology result is immutable';end if;if new.released_at is not null and old.released_at is null then if o.status<>'RESULT_AVAILABLE'then raise exception 'radiology result is not available';end if;new.released_by:=auth.uid();end if;elsif public.can_manage_clinical_booking(o.booking_id)then if new.summary is distinct from old.summary or new.report_notes is distinct from old.report_notes or new.released_at is distinct from old.released_at or new.released_by is distinct from old.released_by then raise exception 'doctor cannot edit radiology result';end if;if old.reviewed_at is not null and(new.reviewed_at is distinct from old.reviewed_at or new.reviewed_by is distinct from old.reviewed_by)then raise exception 'radiology review is immutable';end if;if new.reviewed_at is not null and old.reviewed_at is null then new.reviewed_by:=auth.uid();update public.radiology_orders set status='REVIEWED'where id=o.id and status='RESULT_AVAILABLE';end if;else raise exception 'radiology result update denied';end if;end if;return new;end$$;

create or replace function public.protect_follow_up() returns trigger language plpgsql set search_path='' as $$begin if tg_op='UPDATE'and new.status is distinct from old.status and not((old.status='PLANNED'and new.status in('SCHEDULED','COMPLETED','CANCELLED'))or(old.status='SCHEDULED'and new.status in('COMPLETED','CANCELLED')))then raise exception 'invalid follow-up transition';end if;return new;end$$;
drop trigger if exists followups_transition on public.clinical_follow_ups;create trigger followups_transition before insert or update on public.clinical_follow_ups for each row execute function public.protect_follow_up();

create or replace function public.result_release_event() returns trigger language plpgsql security definer set search_path='' as $$declare booking uuid;kind text;begin if tg_table_name='lab_results'then select booking_id into booking from public.lab_orders where id=new.lab_order_id;else select booking_id into booking from public.radiology_orders where id=new.radiology_order_id;end if;if new.released_at is not null and old.released_at is null then kind:=case when tg_table_name='lab_results'then'lab.result_released'else'radiology.result_released'end;insert into public.journey_events(booking_id,event_type,related_entity_type,related_entity_id,status_label,created_by)values(booking,kind,tg_table_name,new.id,'RELEASED',auth.uid());insert into public.notifications(recipient_id,type,title_key,message_key,related_entity_type,related_entity_id)values(new.patient_id,kind,'part6.notifications.'||replace(kind,'.','')||'Title','part6.notifications.'||replace(kind,'.','')||'Message','booking',booking);elsif new.reviewed_at is not null and old.reviewed_at is null then kind:=case when tg_table_name='lab_results'then'lab.result_reviewed'else'radiology.result_reviewed'end;insert into public.journey_events(booking_id,event_type,related_entity_type,related_entity_id,status_label,created_by)values(booking,kind,tg_table_name,new.id,'REVIEWED',auth.uid());insert into public.notifications(recipient_id,type,title_key,message_key,related_entity_type,related_entity_id)values(new.patient_id,kind,'part6.notifications.resultreviewedTitle','part6.notifications.resultreviewedMessage','booking',booking);end if;return new;end$$;

create or replace function public.can_access_clinical_result_object(object_name text,write_access boolean default false)returns boolean language plpgsql stable security definer set search_path='' as $$declare p text[];patient uuid;kind text;result uuid;begin p:=storage.foldername(object_name);if array_length(p,1)<>3 or object_name!~'^[0-9a-f-]{36}/(lab|radiology)/[0-9a-f-]{36}/[A-Za-z0-9][A-Za-z0-9._-]{0,239}$'then return false;end if;begin patient:=p[1]::uuid;kind:=p[2];result:=p[3]::uuid;exception when invalid_text_representation then return false;end;if kind='lab'then return exists(select 1 from public.lab_results r join public.lab_orders o on o.id=r.lab_order_id where r.id=result and r.patient_id=patient and(case when write_access then public.is_diagnostic_member('MEDICAL_LABORATORY',o.medical_laboratory_id)else public.can_read_lab_result(r)end));elsif kind='radiology'then return exists(select 1 from public.radiology_results r join public.radiology_orders o on o.id=r.radiology_order_id where r.id=result and r.patient_id=patient and(case when write_access then public.is_diagnostic_member('RADIOLOGY_CENTER',o.radiology_center_id)else public.can_read_radiology_result(r)end));end if;return false;end$$;

revoke all on function public.clinical_scope_matches(uuid,uuid,uuid,uuid)from public;grant execute on function public.clinical_scope_matches(uuid,uuid,uuid,uuid)to authenticated;
commit;
