import { revalidatePath } from '@/src/react-app/compat/cache';
import { redirect } from '@/src/react-app/compat/navigation';
import { isLocale,type Locale } from '@/src/i18n/config';
import { requireRoles } from '@/src/lib/auth/context';
import { getSupabaseBrowserClient } from '@/src/lib/supabase/browser';
import { journeyCreateSchema,journeyDeleteSchema,journeyServiceDeleteSchema,journeyServiceSchema,journeyUpdateSchema } from './validation';

export interface CareJourneyActionState{error?:string;success?:string}
const localeOf=(f:FormData):Locale=>{const x=String(f.get('locale')??'en');return isLocale(x)?x:'en'};
const nullable=(x:string|undefined)=>x||null;
async function admin(locale:Locale){return requireRoles(locale,['ADMIN','SUPER_ADMIN']);}
export async function createCareJourneyAction(_:CareJourneyActionState,f:FormData):Promise<CareJourneyActionState>{const locale=localeOf(f);await admin(locale);const parsed=journeyCreateSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'failed'};const v=parsed.data;const{data,error}=await s.rpc('create_admin_care_journey',{target_patient:v.patient_id,target_type:v.journey_type,target_start:nullable(v.expected_start_date),target_end:nullable(v.expected_end_date),target_notes:nullable(v.coordination_notes)});if(error||!data)return{error:'failed'};revalidatePath(`/${locale}/admin/journeys`);redirect(`/${locale}/admin/journeys/${data}`);}
export async function updateCareJourneyAction(_:CareJourneyActionState,f:FormData):Promise<CareJourneyActionState>{const locale=localeOf(f);await admin(locale);const parsed=journeyUpdateSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'failed'};const v=parsed.data;const{error}=await s.from('bookings').update({journey_status:v.journey_status,expected_start_date:nullable(v.expected_start_date),expected_end_date:nullable(v.expected_end_date),planned_arrival:nullable(v.expected_start_date),estimated_completion:nullable(v.expected_end_date),coordination_notes:nullable(v.coordination_notes)}).eq('id',v.journey_id);if(error)return{error:'failed'};revalidatePath(`/${locale}/admin/journeys`);return{success:'saved'};}
export async function saveJourneyServiceAction(_:CareJourneyActionState,f:FormData):Promise<CareJourneyActionState>{const locale=localeOf(f);const context=await admin(locale);const parsed=journeyServiceSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'failed'};const v=parsed.data;const provider=v.provider_id||null;const names:{[K in typeof v.service_type]:string}={DOCTOR_CONSULTATION:'Doctor consultation',HOSPITAL_PROCEDURE:'Surgery / procedure',LABORATORY:'Laboratory service',RADIOLOGY:'Radiology service'};const payload={booking_id:v.journey_id,service_type:v.service_type,selection_state:v.selection_state,status:v.status,title:names[v.service_type],doctor_id:v.service_type==='DOCTOR_CONSULTATION'?provider:null,hospital_id:v.service_type==='HOSPITAL_PROCEDURE'?provider:null,medical_laboratory_id:v.service_type==='LABORATORY'?provider:null,radiology_center_id:v.service_type==='RADIOLOGY'?provider:null,treatment_id:v.service_type==='HOSPITAL_PROCEDURE'?(v.treatment_id||null):null,base_cost:v.base_cost===''?null:v.base_cost,currency:v.currency?String(v.currency).toUpperCase():null,carebridge_fee_percent:v.carebridge_fee_percent,planned_date:nullable(v.planned_date),notes:nullable(v.notes)};const result=v.service_id?await s.from('journey_services').update(payload).eq('id',v.service_id).eq('booking_id',v.journey_id):await s.from('journey_services').insert({...payload,created_by:context.userId});if(result.error)return{error:'failed'};revalidatePath(`/${locale}/admin/journeys/${v.journey_id}`);revalidatePath(`/${locale}/admin/customer-accounts`);return{success:'saved'};}
export async function deleteJourneyServiceAction(_:CareJourneyActionState,f:FormData):Promise<CareJourneyActionState>{const locale=localeOf(f);await admin(locale);const parsed=journeyServiceDeleteSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'failed'};const{error}=await s.from('journey_services').delete().eq('id',parsed.data.service_id).eq('booking_id',parsed.data.journey_id);if(error)return{error:'failed'};revalidatePath(`/${locale}/admin/journeys/${parsed.data.journey_id}`);return{success:'saved'};}
export async function deleteCareJourneyAction(_:CareJourneyActionState,f:FormData):Promise<CareJourneyActionState>{const locale=localeOf(f);await admin(locale);const parsed=journeyDeleteSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const s=await getSupabaseBrowserClient();if(!s)return{error:'failed'};const{error}=await s.from('bookings').delete().eq('id',parsed.data.journey_id);if(error)return{error:'failed'};revalidatePath(`/${locale}/admin/journeys`);redirect(`/${locale}/admin/journeys`);}
