import type { SupabaseClient } from '@supabase/supabase-js';

export type CareJourneyStatus='DRAFT'|'PLANNING'|'READY_FOR_CONFIRMATION'|'CONFIRMED'|'IN_PROGRESS'|'FOLLOW_UP'|'COMPLETED'|'CANCELLED';
export type ServiceType='DOCTOR_CONSULTATION'|'HOSPITAL_PROCEDURE'|'LABORATORY'|'RADIOLOGY';
export interface PatientChoice{id:string;label:string}
export interface JourneyService{id:string;booking_id:string;service_type:ServiceType;selection_state:'ADMIN_SELECTED'|'PATIENT_TO_CHOOSE'|'PATIENT_SELECTED'|'NOT_REQUIRED';status:'PLANNED'|'REQUESTED'|'CONFIRMED'|'IN_PROGRESS'|'COMPLETED'|'CANCELLED'|'ARCHIVED';title:string;doctor_id:string|null;hospital_id:string|null;medical_laboratory_id:string|null;radiology_center_id:string|null;planned_date:string|null;notes:string|null;doctor?:{display_name:string|null;first_name:string;last_name:string}|null;hospital?:{name_i18n:Record<string,string>}|null;laboratory?:{name_i18n:Record<string,string>}|null;radiology?:{name_i18n:Record<string,string>}|null}
export interface CareJourney{id:string;booking_reference:string;patient_id:string;journey_type:'LOCAL_CARE'|'INTERNATIONAL_MEDICAL_TRAVEL';journey_status:CareJourneyStatus;expected_start_date:string|null;expected_end_date:string|null;coordination_notes:string|null;status:string;case_id:string|null;offer_id:string|null;created_at:string;updated_at:string;patient?:{display_name:string|null;first_name:string|null;last_name:string|null}|null;services?:JourneyService[];counts?:{appointments:number;invoices:number;documents:number;events:number;accommodation:number;travel:number};events?:Array<{id:string;event_type:string;status_label:string|null;created_at:string}>}
export interface ClinicalProviders{doctors:Array<{id:string;label:string}>;hospitals:Array<{id:string;label:string}>;laboratories:Array<{id:string;label:string}>;radiology:Array<{id:string;label:string}>}

const profileLabel=(p:{display_name:string|null;first_name:string|null;last_name:string|null})=>p.display_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||'Patient';
export async function loadPatients(s:SupabaseClient):Promise<PatientChoice[]>{const roles=await s.from('user_roles').select('user_id').eq('role','PATIENT');const ids=(roles.data??[]).map(x=>x.user_id);if(!ids.length)return[];const profiles=await s.from('profiles').select('id,display_name,first_name,last_name').in('id',ids).eq('account_status','ACTIVE').order('display_name');return(profiles.data??[]).map(p=>({id:p.id,label:profileLabel(p)}));}
async function attachPatients(s:SupabaseClient,rows:CareJourney[]){const ids=[...new Set(rows.map(x=>x.patient_id))];if(!ids.length)return rows;const{data}=await s.from('profiles').select('id,display_name,first_name,last_name').in('id',ids);const map=new Map((data??[]).map(p=>[p.id,p]));return rows.map(row=>({...row,patient:map.get(row.patient_id)??null}));}
export async function loadCareJourneys(s:SupabaseClient){const{data,error}=await s.from('bookings').select('id,booking_reference,patient_id,journey_type,journey_status,expected_start_date,expected_end_date,coordination_notes,status,case_id,offer_id,created_at,updated_at').order('updated_at',{ascending:false}).limit(200);if(error)throw error;return attachPatients(s,(data??[]) as CareJourney[]);}
export async function loadClinicalProviders(s:SupabaseClient):Promise<ClinicalProviders>{const[d,h,l,r]=await Promise.all([s.from('doctors').select('id,display_name,first_name,last_name').eq('status','ACTIVE').order('display_name').limit(300),s.from('hospitals').select('id,name_i18n').eq('status','ACTIVE').order('legal_name').limit(300),s.from('medical_laboratories').select('id,name_i18n').eq('status','ACTIVE').limit(300),s.from('radiology_centers').select('id,name_i18n').eq('status','ACTIVE').limit(300)]);const localized=(v:Record<string,string>|null)=>v?.en||v?.ar||v?.fr||'Provider';return{doctors:(d.data??[]).map(x=>({id:x.id,label:x.display_name||[x.first_name,x.last_name].filter(Boolean).join(' ')})),hospitals:(h.data??[]).map(x=>({id:x.id,label:localized(x.name_i18n)})),laboratories:(l.data??[]).map(x=>({id:x.id,label:localized(x.name_i18n)})),radiology:(r.data??[]).map(x=>({id:x.id,label:localized(x.name_i18n)}))};}
export async function loadCareJourney(s:SupabaseClient,id:string){const base=await s.from('bookings').select('id,booking_reference,patient_id,journey_type,journey_status,expected_start_date,expected_end_date,coordination_notes,status,case_id,offer_id,created_at,updated_at').eq('id',id).maybeSingle();if(base.error||!base.data)return null;const[services,appointments,invoices,attachments,events,accommodation,travel]=await Promise.all([s.from('journey_services').select('*,doctor:doctors(display_name,first_name,last_name),hospital:hospitals(name_i18n),laboratory:medical_laboratories(name_i18n),radiology:radiology_centers(name_i18n)').eq('booking_id',id).order('created_at'),s.from('appointments').select('id',{count:'exact',head:true}).eq('booking_id',id),s.from('invoices').select('id',{count:'exact',head:true}).eq('booking_id',id),s.from('clinical_attachments').select('id',{count:'exact',head:true}).eq('booking_id',id),s.from('journey_events').select('id,event_type,status_label,created_at').eq('booking_id',id).order('created_at',{ascending:false}).limit(100),s.from('accommodation_bookings').select('id',{count:'exact',head:true}).eq('booking_id',id),s.from('travel_plans').select('id',{count:'exact',head:true}).eq('booking_id',id)]);const rows=await attachPatients(s,[base.data as CareJourney]);return{...rows[0],services:(services.data??[]) as unknown as JourneyService[],events:events.data??[],counts:{appointments:appointments.count??0,invoices:invoices.count??0,documents:attachments.count??0,events:events.data?.length??0,accommodation:accommodation.count??0,travel:travel.count??0}} as CareJourney;}
