'use client';

import { useActionState,useMemo,useState } from 'react';
import Link from '@/src/react-app/compat/link';
import { BedDouble,CalendarDays,ClipboardList,FileText,HeartPulse,Plane,Plus,ReceiptText,Trash2 } from 'lucide-react';
import { Badge } from '@/src/components/ui/badge';
import { Button } from '@/src/components/ui/button';
import { Card,CardContent,CardHeader } from '@/src/components/ui/card';
import { Dialog } from '@/src/components/ui/dialog';
import { Input } from '@/src/components/ui/input';
import { Select } from '@/src/components/ui/select';
import { Textarea } from '@/src/components/ui/textarea';
import type { Locale } from '@/src/i18n/config';
import { createCareJourneyAction,deleteCareJourneyAction,deleteJourneyServiceAction,saveJourneyServiceAction,updateCareJourneyAction,type CareJourneyActionState } from './actions';
import type { CareJourney,ClinicalProviders,JourneyService,PatientChoice,ServiceType } from './data';
import type { CareJourneyDictionary } from './messages';

const initial:CareJourneyActionState={};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-semibold text-slate-700">{label}{children}</label>}
function Feedback({state,copy}:{state:CareJourneyActionState;copy:CareJourneyDictionary}){return state.error?<p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800" role="alert">{state.error==='invalid'?copy.invalid:copy.failed}</p>:state.success?<p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{copy.saved}</p>:null}
const patientName=(j:CareJourney)=>j.patient?.display_name||[j.patient?.first_name,j.patient?.last_name].filter(Boolean).join(' ')||copyFallback;
const copyFallback='Patient';
const date=(locale:Locale,value:string|null)=>value?new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(`${value}T00:00:00`)):'—';

function CreateJourneyForm({copy,locale,patients}:{copy:CareJourneyDictionary;locale:Locale;patients:PatientChoice[]}){const[state,action,pending]=useActionState(createCareJourneyAction,initial);return <form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><Feedback copy={copy} state={state}/><Field label={copy.patient}><Select name="patient_id" required><option value="">—</option>{patients.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</Select></Field><Field label={copy.journeyType}><Select name="journey_type"><option value="LOCAL_CARE">{copy.local}</option><option value="INTERNATIONAL_MEDICAL_TRAVEL">{copy.international}</option></Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={copy.start}><Input name="expected_start_date" type="date"/></Field><Field label={copy.end}><Input name="expected_end_date" type="date"/></Field></div><Field label={copy.notes}><Textarea maxLength={4000} name="coordination_notes"/></Field><Button disabled={!patients.length} loading={pending}>{copy.newJourney}</Button></form>}

export function CareJourneyList({copy,journeys,locale,patients}:{copy:CareJourneyDictionary;journeys:CareJourney[];locale:Locale;patients:PatientChoice[]}){const[open,setOpen]=useState(false);return <div className="space-y-6"><div className="flex justify-end"><Button onClick={()=>setOpen(true)} type="button"><Plus className="size-4"/>{copy.newJourney}</Button></div>{journeys.length?<div className="grid gap-4 lg:grid-cols-2">{journeys.map(j=><Card key={j.id} variant="interactive"><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs font-semibold text-blue-700">{j.booking_reference}</p><h2 className="mt-1 text-lg font-semibold text-slate-950">{patientName(j)}</h2><p className="mt-1 text-sm text-slate-500">{j.journey_type==='LOCAL_CARE'?copy.local:copy.international}</p></div><Badge variant={j.journey_status==='CANCELLED'?'slate':j.journey_status==='COMPLETED'?'green':'blue'}>{copy.statuses[j.journey_status]}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm"><div><span className="text-slate-500">{copy.start}</span><p className="mt-1 font-medium">{date(locale,j.expected_start_date)}</p></div><div><span className="text-slate-500">{copy.end}</span><p className="mt-1 font-medium">{date(locale,j.expected_end_date)}</p></div></div><Link className="mt-4 inline-flex min-h-10 w-full items-center justify-center rounded-xl border border-slate-200 px-4 text-sm font-semibold text-slate-800 hover:bg-slate-50" href={`/${locale}/admin/journeys/${j.id}`}>{copy.open}</Link></CardContent></Card>)}</div>:<Card><CardContent className="py-14 text-center text-sm text-slate-500">{copy.empty}</CardContent></Card>}<Dialog closeLabel={copy.close} description={copy.description} onClose={()=>setOpen(false)} open={open} title={copy.newJourney}><CreateJourneyForm copy={copy} locale={locale} patients={patients}/></Dialog></div>}

const providerRows=(providers:ClinicalProviders,type:ServiceType)=>type==='DOCTOR_CONSULTATION'?providers.doctors:type==='HOSPITAL_PROCEDURE'?providers.hospitals:type==='LABORATORY'?providers.laboratories:providers.radiology;
function providerId(service:JourneyService){return service.doctor_id||service.hospital_id||service.medical_laboratory_id||service.radiology_center_id||''}
function ServiceForm({copy,journeyId,locale,providers,service}:{copy:CareJourneyDictionary;journeyId:string;locale:Locale;providers:ClinicalProviders;service?:JourneyService|null}){const[state,action,pending]=useActionState(saveJourneyServiceAction,initial);const[type,setType]=useState<ServiceType>(service?.service_type??'DOCTOR_CONSULTATION');const[selection,setSelection]=useState(service?.selection_state??'ADMIN_SELECTED');const rows=providerRows(providers,type);return <form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><input name="journey_id" type="hidden" value={journeyId}/><input name="service_id" type="hidden" value={service?.id??''}/><Feedback copy={copy} state={state}/><Field label={copy.serviceType}><Select name="service_type" onChange={e=>setType(e.target.value as ServiceType)} value={type}><option value="DOCTOR_CONSULTATION">{copy.doctor}</option><option value="HOSPITAL_PROCEDURE">{copy.hospital}</option><option value="LABORATORY">{copy.laboratory}</option><option value="RADIOLOGY">{copy.radiology}</option></Select></Field><Field label={copy.selection}><Select name="selection_state" onChange={e=>setSelection(e.target.value as JourneyService['selection_state'])} value={selection}><option value="ADMIN_SELECTED">{copy.adminSelected}</option><option value="PATIENT_TO_CHOOSE">{copy.patientChoose}</option><option value="PATIENT_SELECTED">{copy.patientSelected}</option><option value="NOT_REQUIRED">{copy.notRequired}</option></Select></Field>{['ADMIN_SELECTED','PATIENT_SELECTED'].includes(selection)?<Field label={copy.provider}><Select defaultValue={service?providerId(service):''} name="provider_id" required><option value="">—</option>{rows.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</Select></Field>:<input name="provider_id" type="hidden" value=""/>}<Field label={copy.serviceType}><Input defaultValue={service?.title??''} maxLength={240} name="title" required/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={copy.status}><Select defaultValue={service?.status??(selection==='NOT_REQUIRED'?'PLANNED':'REQUESTED')} name="status"><option value="PLANNED">PLANNED</option><option value="REQUESTED">REQUESTED</option><option value="CONFIRMED">CONFIRMED</option><option value="IN_PROGRESS">IN PROGRESS</option><option value="COMPLETED">COMPLETED</option><option value="CANCELLED">CANCELLED</option><option value="ARCHIVED">ARCHIVED</option></Select></Field><Field label={copy.plannedDate}><Input defaultValue={service?.planned_date??''} name="planned_date" type="date"/></Field></div><Field label={copy.notes}><Textarea defaultValue={service?.notes??''} maxLength={3000} name="notes"/></Field><Button loading={pending}>{copy.save}</Button></form>}

function Overview({copy,journey,locale}:{copy:CareJourneyDictionary;journey:CareJourney;locale:Locale}){const[state,action,pending]=useActionState(updateCareJourneyAction,initial);const[removeState,removeAction,removing]=useActionState(deleteCareJourneyAction,initial);return <div className="grid gap-6 xl:grid-cols-[1fr_22rem]"><Card variant="form"><CardHeader><h2 className="text-lg font-semibold">{copy.overview}</h2></CardHeader><CardContent><form action={action} className="grid gap-4"><input name="locale" type="hidden" value={locale}/><input name="journey_id" type="hidden" value={journey.id}/><Feedback copy={copy} state={state}/><Field label={copy.status}><Select defaultValue={journey.journey_status} name="journey_status">{Object.entries(copy.statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={copy.start}><Input defaultValue={journey.expected_start_date??''} name="expected_start_date" type="date"/></Field><Field label={copy.end}><Input defaultValue={journey.expected_end_date??''} name="expected_end_date" type="date"/></Field></div><Field label={copy.notes}><Textarea defaultValue={journey.coordination_notes??''} maxLength={4000} name="coordination_notes"/></Field><Button loading={pending}>{copy.save}</Button></form></CardContent></Card><div className="space-y-4"><Card><CardContent className="p-5"><p className="text-sm text-slate-500">{copy.patient}</p><p className="mt-1 font-semibold">{patientName(journey)}</p><p className="mt-4 text-sm text-slate-500">{copy.reference}</p><p className="mt-1 font-mono text-sm font-semibold">{journey.booking_reference}</p></CardContent></Card><Card className="border-amber-200 bg-amber-50/50"><CardContent className="p-5 text-sm leading-6 text-amber-900">{copy.clinicalRequired}</CardContent></Card>{['DRAFT','PLANNING'].includes(journey.journey_status)?<form action={removeAction}><input name="locale" type="hidden" value={locale}/><input name="journey_id" type="hidden" value={journey.id}/><Feedback copy={copy} state={removeState}/><Button className="w-full" loading={removing} variant="danger"><Trash2 className="size-4"/>{copy.deleteJourney}</Button></form>:<p className="text-xs leading-5 text-slate-500">{copy.deleteBlocked}</p>}</div></div>}

function Clinical({copy,journey,locale,providers}:{copy:CareJourneyDictionary;journey:CareJourney;locale:Locale;providers:ClinicalProviders}){const[open,setOpen]=useState(false);const[editing,setEditing]=useState<JourneyService|null>(null);return <div className="space-y-5"><div className="flex justify-end"><Button onClick={()=>{setEditing(null);setOpen(true)}} type="button"><Plus className="size-4"/>{copy.addService}</Button></div>{journey.services?.length?<div className="grid gap-4 lg:grid-cols-2">{journey.services.map(s=><Card key={s.id}><CardContent className="p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">{s.service_type.replaceAll('_',' ')}</p><h3 className="mt-1 font-semibold">{s.title}</h3><p className="mt-2 text-sm text-slate-500">{s.selection_state.replaceAll('_',' ')}</p></div><Badge variant={s.status==='COMPLETED'?'green':s.status==='CANCELLED'?'slate':'blue'}>{s.status.replaceAll('_',' ')}</Badge></div><div className="mt-4 flex gap-2"><Button onClick={()=>{setEditing(s);setOpen(true)}} size="sm" type="button" variant="outline">{copy.edit}</Button>{['PLANNED','CANCELLED','ARCHIVED'].includes(s.status)?<DeleteService copy={copy} journeyId={journey.id} locale={locale} serviceId={s.id}/>:null}</div></CardContent></Card>)}</div>:<Card><CardContent className="py-12 text-center text-sm text-slate-500">{copy.noRecords}</CardContent></Card>}<Dialog closeLabel={copy.close} description={copy.clinicalRequired} onClose={()=>setOpen(false)} open={open} title={editing?copy.edit:copy.addService}><ServiceForm copy={copy} journeyId={journey.id} locale={locale} providers={providers} service={editing}/></Dialog></div>}
function DeleteService({copy,journeyId,locale,serviceId}:{copy:CareJourneyDictionary;journeyId:string;locale:Locale;serviceId:string}){const[state,action,pending]=useActionState(deleteJourneyServiceAction,initial);return <form action={action}><input name="locale" type="hidden" value={locale}/><input name="journey_id" type="hidden" value={journeyId}/><input name="service_id" type="hidden" value={serviceId}/><Button loading={pending} size="sm" variant="ghost"><Trash2 className="size-4"/>{state.error?copy.deleteBlocked:copy.delete}</Button></form>}

const tabs=[['overview','overview',ClipboardList],['clinical','clinical',HeartPulse],['schedule','schedule',CalendarDays],['accommodation','accommodation',BedDouble],['travel','travel',Plane],['payments','payments',ReceiptText],['documents','documents',FileText],['timeline','timeline',ClipboardList]] as const;
export function CareJourneyWorkspace({copy,journey,locale,providers}:{copy:CareJourneyDictionary;journey:CareJourney;locale:Locale;providers:ClinicalProviders}){const[tab,setTab]=useState<(typeof tabs)[number][0]>('overview');const summary=useMemo(()=>[{id:'schedule',count:journey.counts?.appointments??0,label:copy.appointments,href:`/${locale}/admin/journeys/${journey.id}`},{id:'accommodation',count:journey.counts?.accommodation??0,label:copy.accommodation,href:`/${locale}/admin/accommodation`},{id:'travel',count:journey.counts?.travel??0,label:copy.travel,href:`/${locale}/admin/travel`},{id:'payments',count:journey.counts?.invoices??0,label:copy.invoices,href:`/${locale}/admin/journeys/${journey.id}`},{id:'documents',count:journey.counts?.documents??0,label:copy.documents,href:`/${locale}/admin/journeys/${journey.id}`}],[copy,journey,locale]);return <div className="space-y-6"><div className="overflow-x-auto"><div className="flex min-w-max gap-2 rounded-2xl border bg-white p-2">{tabs.map(([id,key,Icon])=><button className={`inline-flex min-h-10 items-center gap-2 rounded-xl px-3.5 text-sm font-semibold ${tab===id?'bg-blue-50 text-blue-800':'text-slate-500 hover:bg-slate-50'}`} key={id} onClick={()=>setTab(id)} type="button"><Icon className="size-4"/>{copy[key]}</button>)}</div></div>{tab==='overview'?<Overview copy={copy} journey={journey} locale={locale}/>:tab==='clinical'?<Clinical copy={copy} journey={journey} locale={locale} providers={providers}/>:tab==='timeline'?<Card><CardHeader><h2 className="font-semibold">{copy.timeline}</h2></CardHeader><CardContent><div className="space-y-3">{journey.events?.length?journey.events.map(e=><div className="border-s-2 border-blue-200 ps-4" key={e.id}><p className="font-medium">{e.event_type.replaceAll('_',' ').replaceAll('.',' · ')}</p><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(e.created_at))}</p></div>):<p className="text-sm text-slate-500">{copy.noRecords}</p>}</div></CardContent></Card>:<div className="grid gap-4 md:grid-cols-2">{summary.filter(x=>x.id===tab).map(x=><Card key={x.id}><CardContent className="p-6"><p className="text-sm text-slate-500">{x.label}</p><p className="mt-2 text-3xl font-bold">{x.count}</p>{['accommodation','travel'].includes(x.id)?<Link className="mt-5 inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-200 px-4 text-sm font-semibold hover:bg-slate-50" href={x.href}>{copy.viewModule}</Link>:null}</CardContent></Card>)}</div>}</div>}
