import {revalidatePath} from '@/src/react-app/compat/cache';
import {isLocale,type Locale} from '@/src/i18n/config';
import {requireRoles} from '@/src/lib/auth/context';
import {getSupabaseBrowserClient} from '@/src/lib/supabase/browser';
import {customerPaymentSchema,financeItemSchema,financeItemUpdateSchema,invoiceActionSchema} from './validation';

export interface CustomerFinanceActionState{error?:'invalid'|'failed';success?:'saved'}
const admin=['ADMIN','SUPER_ADMIN'] as const;
const localeOf=(f:FormData):Locale=>{const value=String(f.get('locale')??'en');return isLocale(value)?value:'en'};
const nil=(value:string|undefined)=>value||null;
const refresh=(locale:Locale,patientId:string)=>{revalidatePath(`/${locale}/admin/customer-accounts`);revalidatePath(`/${locale}/admin/customer-accounts/${patientId}`);revalidatePath(`/${locale}/patient/journeys`);};
async function context(bookingId:string){const s=await getSupabaseBrowserClient();if(!s)return null;const{data}=await s.from('bookings').select('id,patient_id,offer_id,provider_type,hospital_id,pharmacy_id,radiology_center_id,medical_laboratory_id').eq('id',bookingId).maybeSingle();return data?{s,booking:data}:null;}
export async function createCustomerFinanceItemAction(_:CustomerFinanceActionState,f:FormData):Promise<CustomerFinanceActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,admin);const parsed=financeItemSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const ctx=await context(parsed.data.booking_id);if(!ctx)return{error:'failed'};const v=parsed.data;const{data:invoice,error}=await ctx.s.from('invoices').insert({invoice_number:`CBI-${crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase()}`,booking_id:ctx.booking.id,offer_id:ctx.booking.offer_id,patient_id:ctx.booking.patient_id,provider_type:ctx.booking.provider_type,hospital_id:ctx.booking.hospital_id,pharmacy_id:ctx.booking.pharmacy_id,radiology_center_id:ctx.booking.radiology_center_id,medical_laboratory_id:ctx.booking.medical_laboratory_id,currency:v.currency,due_date:nil(v.due_date),notes:nil(v.notes),created_by:auth.userId}).select('id').single();if(error||!invoice)return{error:'failed'};const item=await ctx.s.from('invoice_items').insert({invoice_id:invoice.id,description:v.description,service_category:v.service_category,quantity:v.quantity,unit_amount:v.base_unit_amount,base_unit_amount:v.base_unit_amount,carebridge_fee_percent:30});if(item.error)return{error:'failed'};refresh(locale,ctx.booking.patient_id);return{success:'saved'};}
export async function updateCustomerFinanceItemAction(_:CustomerFinanceActionState,f:FormData):Promise<CustomerFinanceActionState>{const locale=localeOf(f);await requireRoles(locale,admin);const parsed=financeItemUpdateSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const ctx=await context(parsed.data.booking_id);if(!ctx)return{error:'failed'};const v=parsed.data;const result=await ctx.s.from('invoice_items').update({description:v.description,service_category:v.service_category,quantity:v.quantity,unit_amount:v.base_unit_amount,base_unit_amount:v.base_unit_amount}).eq('id',v.item_id).eq('invoice_id',v.invoice_id);if(result.error)return{error:'failed'};refresh(locale,ctx.booking.patient_id);return{success:'saved'};}
export async function issueCustomerInvoiceAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,admin);const parsed=invoiceActionSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return;const ctx=await context(parsed.data.booking_id);if(!ctx)return;await ctx.s.from('invoices').update({status:'ISSUED'}).eq('id',parsed.data.invoice_id).eq('booking_id',ctx.booking.id).eq('status','DRAFT');refresh(locale,ctx.booking.patient_id);}
export async function cancelCustomerInvoiceAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,admin);const parsed=invoiceActionSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return;const ctx=await context(parsed.data.booking_id);if(!ctx)return;await ctx.s.from('invoices').update({status:'CANCELLED'}).eq('id',parsed.data.invoice_id).eq('booking_id',ctx.booking.id).in('status',['DRAFT','ISSUED','PARTIALLY_PAID','OVERDUE']);refresh(locale,ctx.booking.patient_id);}
export async function deleteCustomerDraftInvoiceAction(f:FormData){const locale=localeOf(f);await requireRoles(locale,admin);const parsed=invoiceActionSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return;const ctx=await context(parsed.data.booking_id);if(!ctx)return;await ctx.s.from('invoices').delete().eq('id',parsed.data.invoice_id).eq('booking_id',ctx.booking.id).eq('status','DRAFT');refresh(locale,ctx.booking.patient_id);}
export async function recordCustomerPaymentAction(_:CustomerFinanceActionState,f:FormData):Promise<CustomerFinanceActionState>{const locale=localeOf(f);const auth=await requireRoles(locale,admin);const parsed=customerPaymentSchema.safeParse(Object.fromEntries(f));if(!parsed.success)return{error:'invalid'};const ctx=await context(parsed.data.booking_id);if(!ctx)return{error:'failed'};const{data:invoice}=await ctx.s.from('invoices').select('currency,total_amount,amount_paid,status').eq('id',parsed.data.invoice_id).eq('booking_id',ctx.booking.id).maybeSingle();if(!invoice||!['ISSUED','PARTIALLY_PAID','OVERDUE'].includes(invoice.status)||parsed.data.amount>Number(invoice.total_amount)-Number(invoice.amount_paid))return{error:'invalid'};const result=await ctx.s.from('payment_records').insert({invoice_id:parsed.data.invoice_id,booking_id:ctx.booking.id,patient_id:ctx.booking.patient_id,amount:parsed.data.amount,currency:invoice.currency,paid_at:new Date(parsed.data.paid_at).toISOString(),method:parsed.data.method,reference_number:nil(parsed.data.reference_number),recorded_by:auth.userId});if(result.error)return{error:'failed'};refresh(locale,ctx.booking.patient_id);return{success:'saved'};}
